"""Python automation interface for the KIM plasma-response solver."""

from kim.config import (
    BuiltinPlasma,
    CollisionModel,
    ElectrostaticPeriodicRun,
    ElectrostaticRun,
    ExplicitPlasma,
    Flr2Config,
    Flr2Run,
    GridConfig,
    GridSpacing,
    IOConfig,
    IonCollisionModel,
    IonSpecies,
    PeriodicConfig,
    PhysicsConfig,
    PlasmaConfig,
    PlasmaIsotope,
    ProfileConfig,
    QuadpackAlgorithm,
    RunConfig,
    RunType,
    SetupConfig,
    SimulationConfig,
    ThetaIntegration,
)
from kim.conventions import (
    ConventionError,
    ConversionOperation,
    ConversionReport,
    ConvertedInputs,
    SourceMetadata,
    convert_from_kim,
    convert_inputs,
    convert_quantity,
    reconstruct_fourier,
    reconstruct_fourier_derivative,
    resonance_target,
)
from kim.diagnostics import EnvironmentDiagnosticReport, diagnose_environment
from kim.errors import (
    ConfigurationError,
    ExecutableError,
    ExperimentalInputError,
    KimError,
    ProfileError,
    ResultError,
    RunError,
    SweepError,
)
from kim.examples import create_example
from kim.executable import (
    ExecutableSelection,
    KamelGitMetadata,
    discover_kamel_git_metadata,
    executable_sha256,
    resolve_executable,
    select_executable,
)
from kim.importers import (
    ExperimentalProfile,
    MarsFInput,
    MarsFMetadata,
    read_marsf_profiles,
)
from kim.preparation import PreparedExperimentalCase, prepare_marsf_case
from kim.profiles import ProfileCopy, ProfileData, ProfileSet, ProfileValidation
from kim.results import DatasetMetadata, PeriodicResult, Result
from kim.runs import (
    InputArtifact,
    RunFailure,
    RunManifest,
    RunPaths,
    RunRepository,
    RunStatus,
)
from kim.simulation import PreparedSimulation, RunResult, Simulation
from kim.sweep import (
    LinearRange,
    ParameterSweep,
    ProfileScale,
    SweepManifest,
    SweepResult,
    SweepSpec,
    SweepStatus,
    run_sweep,
)

__version__ = "0.1.0"

__all__ = [
    "BuiltinPlasma",
    "CollisionModel",
    "ConversionOperation",
    "ConversionReport",
    "ConvertedInputs",
    "ConventionError",
    "ConfigurationError",
    "DatasetMetadata",
    "ElectrostaticPeriodicRun",
    "ElectrostaticRun",
    "EnvironmentDiagnosticReport",
    "ExplicitPlasma",
    "ExecutableError",
    "ExecutableSelection",
    "ExperimentalInputError",
    "ExperimentalProfile",
    "Flr2Config",
    "Flr2Run",
    "GridConfig",
    "GridSpacing",
    "IOConfig",
    "IonCollisionModel",
    "IonSpecies",
    "InputArtifact",
    "KamelGitMetadata",
    "KimError",
    "LinearRange",
    "MarsFInput",
    "MarsFMetadata",
    "PeriodicConfig",
    "PeriodicResult",
    "ParameterSweep",
    "PlasmaConfig",
    "PhysicsConfig",
    "PlasmaIsotope",
    "ProfileConfig",
    "ProfileCopy",
    "ProfileData",
    "ProfileError",
    "ProfileSet",
    "ProfileValidation",
    "PreparedExperimentalCase",
    "ProfileScale",
    "PreparedSimulation",
    "QuadpackAlgorithm",
    "Result",
    "ResultError",
    "RunConfig",
    "RunError",
    "RunFailure",
    "RunManifest",
    "RunPaths",
    "RunRepository",
    "RunResult",
    "RunStatus",
    "RunType",
    "SetupConfig",
    "SimulationConfig",
    "SourceMetadata",
    "Simulation",
    "SweepError",
    "SweepManifest",
    "SweepResult",
    "SweepSpec",
    "SweepStatus",
    "ThetaIntegration",
    "__version__",
    "discover_kamel_git_metadata",
    "create_example",
    "convert_inputs",
    "convert_from_kim",
    "convert_quantity",
    "diagnose_environment",
    "executable_sha256",
    "resolve_executable",
    "select_executable",
    "run_sweep",
    "reconstruct_fourier",
    "reconstruct_fourier_derivative",
    "resonance_target",
    "read_marsf_profiles",
    "prepare_marsf_case",
]
