"""Python automation interface for the KIM plasma-response solver."""

from kim.config import (
    BuiltinPlasma,
    CollisionModel,
    ElectrostaticPeriodicRun,
    ElectrostaticRun,
    ExplicitPlasma,
    Flr2Config,
    Flr2Run,
    GridConfig,
    GridSpacing,
    IOConfig,
    IonCollisionModel,
    IonSpecies,
    PeriodicConfig,
    PhysicsConfig,
    PlasmaConfig,
    PlasmaIsotope,
    ProfileConfig,
    QuadpackAlgorithm,
    RunConfig,
    RunType,
    SetupConfig,
    SimulationConfig,
    ThetaIntegration,
)
from kim.condor import (
    JparCurrentMetric,
    KimCondorJob,
    KimCondorPlan,
    KimCondorScanResults,
    collect_condor_sweep,
    stage_condor_sweep,
    submit_condor_sweep,
    wait_condor_sweep,
)
from kim.errors import (
    ConfigurationError,
    ExecutableError,
    KimError,
    ProfileError,
    ResultError,
    RunError,
    SweepError,
)
from kim.executable import (
    KamelGitMetadata,
    discover_kamel_git_metadata,
    executable_sha256,
    resolve_executable,
)
from kim.profiles import ProfileCopy, ProfileData, ProfileSet, ProfileValidation
from kim.results import DatasetMetadata, PeriodicResult, Result
from kim.runs import (
    InputArtifact,
    RunFailure,
    RunManifest,
    RunPaths,
    RunRepository,
    RunStatus,
)
from kim.simulation import PreparedSimulation, RunResult, Simulation
from kim.sweep import (
    LinearRange,
    ParameterSweep,
    ProfileScale,
    SweepManifest,
    SweepResult,
    SweepSpec,
    SweepStatus,
    run_sweep,
)

__version__ = "0.1.0"

__all__ = [
    "BuiltinPlasma",
    "CollisionModel",
    "ConfigurationError",
    "DatasetMetadata",
    "ElectrostaticPeriodicRun",
    "ElectrostaticRun",
    "ExplicitPlasma",
    "ExecutableError",
    "Flr2Config",
    "Flr2Run",
    "GridConfig",
    "GridSpacing",
    "IOConfig",
    "IonCollisionModel",
    "IonSpecies",
    "InputArtifact",
    "JparCurrentMetric",
    "KamelGitMetadata",
    "KimError",
    "KimCondorJob",
    "KimCondorPlan",
    "KimCondorScanResults",
    "LinearRange",
    "PeriodicConfig",
    "PeriodicResult",
    "ParameterSweep",
    "PlasmaConfig",
    "PhysicsConfig",
    "PlasmaIsotope",
    "ProfileConfig",
    "ProfileCopy",
    "ProfileData",
    "ProfileError",
    "ProfileSet",
    "ProfileValidation",
    "ProfileScale",
    "PreparedSimulation",
    "QuadpackAlgorithm",
    "Result",
    "ResultError",
    "RunConfig",
    "RunError",
    "RunFailure",
    "RunManifest",
    "RunPaths",
    "RunRepository",
    "RunResult",
    "RunStatus",
    "RunType",
    "SetupConfig",
    "SimulationConfig",
    "Simulation",
    "SweepError",
    "SweepManifest",
    "SweepResult",
    "SweepSpec",
    "SweepStatus",
    "ThetaIntegration",
    "__version__",
    "discover_kamel_git_metadata",
    "collect_condor_sweep",
    "executable_sha256",
    "resolve_executable",
    "run_sweep",
    "stage_condor_sweep",
    "submit_condor_sweep",
    "wait_condor_sweep",
]
