"""Canonical boundary between validated Python configuration and KIM namelists."""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path
from typing import Any

import f90nml
from kim.config import (
    BuiltinPlasma,
    ElectrostaticPeriodicRun,
    ExplicitPlasma,
    Flr2Run,
    GridConfig,
    IOConfig,
    IonSpecies,
    PeriodicConfig,
    PhysicsConfig,
    ProfileConfig,
    SetupConfig,
    SimulationConfig,
)
from kim.errors import ConfigurationError
from pydantic import ValidationError

_HEADER = "! Generated by kamel-kim 0.1.0; manifest schema 1\n"
_MANDATORY_GROUPS = (
    "kim_config",
    "wkb_dispersion",
    "kim_io",
    "kim_setup",
    "kim_grid",
    "kim_profiles",
)
_SUPPORTED_KEYS = {
    "kim_config": {
        "number_of_ion_species",
        "artificial_debye_case",
        "type_of_run",
        "collision_model",
        "read_species_from_namelist",
        "ion_collision_model",
        "collisionless_kpar_epsilon",
        "ion_fp_collision_scale",
        "turn_off_ions",
        "turn_off_electrons",
        "plasma_type",
        "rescale_density",
        "number_density_rescale",
        "ion_flr_scale_factor",
        "collision_frequency_scale",
        "boole_energy_conservation",
    },
    "wkb_dispersion": set(),
    "kim_io": {
        "profile_location",
        "output_path",
        "hdf5_input",
        "hdf5_output",
        "log_level",
        "data_verbosity",
        "calculate_asymptotics",
        "h5_out_file",
        "write_diagnostics_dat",
    },
    "kim_setup": {
        "btor",
        "r0",
        "m_mode",
        "n_mode",
        "omega",
        "spline_base",
        "type_br_field",
        "collisions_off",
        "set_profiles_constant",
        "bc_type",
        "mphi_max",
        "br_boundary_re",
        "br_boundary_im",
    },
    "kim_grid": {
        "grid_spacing_rg",
        "grid_spacing_xl",
        "l_space_dim",
        "theta_integration",
        "rg_space_dim",
        "larmor_skip_factor",
        "gauss_int_nodes_ntheta",
        "gauss_int_nodes_nx",
        "gauss_int_nodes_nxp",
        "r_plas",
        "r_min",
        "width_res",
        "ampl_res",
        "hrmax_scaling",
        "rkf45_atol",
        "rkf45_rtol",
        "kernel_taper_skip_threshold",
        "quadpack_algorithm",
        "quadpack_key",
        "quadpack_limit",
        "quadpack_epsabs",
        "quadpack_epsrel",
        "quadpack_use_u_substitution",
    },
    "kim_profiles": {
        "coord_type",
        "input_profile_dir",
        "n_file",
        "te_file",
        "ti_file",
        "vz_file",
        "er_file",
        "q_file",
    },
    "kim_periodic": {
        "periodic_dr_asis_scale",
        "periodic_dr_tr_scale",
        "periodic_kmax_scale",
        "periodic_n_rg",
        "periodic_match_global_kernel_approximations",
    },
    "kim_flr2": {
        "flr2_electron_flr",
        "flr2_ion_flr",
        "flr2_electron_potential",
        "flr2_ion_potential",
        "flr2_electron_current",
        "flr2_ion_current",
        "flr2_include_potential_in_current",
    },
    "kim_species": {"ai", "zi"},
}


def dumps_namelist(
    config: SimulationConfig,
    *,
    profile_directory: Path | str | None = None,
    output_directory: Path | str = "./results",
    output_file: str = "KIM_output.h5",
) -> str:
    """Render a deterministic namelist for one validated simulation."""

    groups = _to_groups(
        config,
        profile_directory=Path(profile_directory or config.profiles.directory),
        output_directory=Path(output_directory),
        output_file=output_file,
    )
    rendered = _HEADER + "".join(_render_group(name, values) for name, values in groups)
    return rendered.rstrip() + "\n"


def write_namelist(
    config: SimulationConfig,
    path: Path | str,
    **operational_values: Any,
) -> Path:
    """Write a canonical namelist and return its path."""

    destination = Path(path)
    destination.write_text(dumps_namelist(config, **operational_values))
    return destination


def load_namelist(path: Path | str) -> SimulationConfig:
    """Parse a supported namelist into the validated public model."""

    source = Path(path)
    try:
        raw = f90nml.read(source).todict()
    except (OSError, ValueError, StopIteration) as error:
        raise ConfigurationError(f"could not read KIM namelist {source}: {error}") from error

    groups = {str(name).lower(): _lower_keys(values) for name, values in raw.items()}
    _validate_contract(groups)
    try:
        return _from_groups(groups)
    except (KeyError, TypeError, ValueError, ValidationError) as error:
        raise ConfigurationError(f"invalid KIM namelist {source}: {error}") from error


def _to_groups(
    config: SimulationConfig,
    *,
    profile_directory: Path,
    output_directory: Path,
    output_file: str,
) -> list[tuple[str, dict[str, Any]]]:
    physics = config.physics
    setup = config.setup
    grid = config.grid
    profiles = config.profiles
    density_scale = physics.density_scale
    builtin = isinstance(config.plasma, BuiltinPlasma)

    profile_path = profile_directory.as_posix().rstrip("/") + "/"
    groups: list[tuple[str, dict[str, Any]]] = [
        (
            "KIM_CONFIG",
            {
                "number_of_ion_species": config.number_of_ion_species,
                "artificial_debye_case": physics.artificial_debye_case,
                "type_of_run": config.run.run_type.value,
                "collision_model": physics.collision_model.value,
                "read_species_from_namelist": not builtin,
                "ion_collision_model": physics.ion_collision_model.value,
                "collisionless_kpar_epsilon": physics.collisionless_kpar_epsilon or -1.0,
                "ion_fp_collision_scale": physics.ion_fp_collision_scale,
                "turn_off_ions": physics.turn_off_ions,
                "turn_off_electrons": physics.turn_off_electrons,
                "plasma_type": config.plasma.isotope.value if builtin else "D",
                "rescale_density": density_scale is not None,
                "number_density_rescale": density_scale or 1.0,
                "ion_flr_scale_factor": physics.ion_larmor_radius_scale,
                "collision_frequency_scale": physics.collision_frequency_scale,
                "boole_energy_conservation": physics.conserve_energy,
            },
        ),
        ("WKB_DISPERSION", {}),
        (
            "KIM_IO",
            {
                "profile_location": profile_path,
                "output_path": str(output_directory),
                "hdf5_input": config.io.hdf5_input,
                "hdf5_output": config.io.hdf5_output,
                "log_level": config.io.log_level,
                "data_verbosity": config.io.data_verbosity,
                "calculate_asymptotics": config.io.calculate_asymptotics,
                "h5_out_file": output_file,
                "write_diagnostics_dat": config.io.write_diagnostics_dat,
            },
        ),
        ("KIM_SETUP", _setup_values(setup)),
        ("KIM_GRID", _grid_values(grid)),
        (
            "KIM_PROFILES",
            {
                "coord_type": profiles.coordinate_type,
                "input_profile_dir": profile_path,
                "n_file": profiles.density_file,
                "Te_file": profiles.electron_temperature_file,
                "Ti_file": profiles.ion_temperature_file,
                "Vz_file": profiles.toroidal_velocity_file,
                "Er_file": profiles.radial_electric_field_file,
                "q_file": profiles.safety_factor_file,
            },
        ),
    ]
    if isinstance(config.run, ElectrostaticPeriodicRun):
        groups.append(("KIM_PERIODIC", _periodic_values(config.run.periodic)))
    if isinstance(config.run, Flr2Run):
        groups.append(("KIM_FLR2", _flr2_values(config.run)))
    if isinstance(config.plasma, ExplicitPlasma):
        groups.append(
            (
                "KIM_SPECIES",
                {
                    "ai": [ion.mass_number for ion in config.plasma.ions],
                    "zi": [ion.charge_number for ion in config.plasma.ions],
                },
            )
        )
    return groups


def _setup_values(setup: SetupConfig) -> dict[str, Any]:
    return {
        "btor": setup.btor,
        "R0": setup.major_radius,
        "m_mode": setup.m_mode,
        "n_mode": setup.n_mode,
        "omega": setup.frequency,
        "spline_base": setup.spline_base,
        "type_br_field": setup.magnetic_perturbation_type,
        "collisions_off": setup.collisions_off,
        "set_profiles_constant": setup.constant_profile_mode,
        "bc_type": setup.boundary_condition,
        "mphi_max": setup.cyclotron_harmonics,
        "Br_boundary_re": setup.br_boundary_real,
        "Br_boundary_im": setup.br_boundary_imag,
    }


def _grid_values(grid: GridConfig) -> dict[str, Any]:
    return {
        "grid_spacing_rg": grid.rg_spacing.value,
        "grid_spacing_xl": grid.l_spacing.value,
        "l_space_dim": grid.l_space_dim,
        "theta_integration": grid.theta_integration.value,
        "rg_space_dim": grid.rg_space_dim,
        "Larmor_skip_factor": grid.larmor_skip_factor,
        "gauss_int_nodes_Ntheta": grid.gauss_nodes_theta,
        "gauss_int_nodes_Nx": grid.gauss_nodes_x,
        "gauss_int_nodes_Nxp": grid.gauss_nodes_x_prime,
        "r_plas": grid.plasma_radius,
        "r_min": grid.radial_minimum,
        "width_res": grid.resonance_width,
        "ampl_res": grid.resonance_amplification,
        "hrmax_scaling": grid.maximum_step_scale,
        "rkf45_atol": grid.rkf45_absolute_tolerance,
        "rkf45_rtol": grid.rkf45_relative_tolerance,
        "kernel_taper_skip_threshold": grid.kernel_taper_skip_threshold,
        "quadpack_algorithm": grid.quadpack_algorithm.value,
        "quadpack_key": grid.quadpack_key,
        "quadpack_limit": grid.quadpack_limit,
        "quadpack_epsabs": grid.quadpack_absolute_tolerance,
        "quadpack_epsrel": grid.quadpack_relative_tolerance,
        "quadpack_use_u_substitution": grid.quadpack_use_u_substitution,
    }


def _periodic_values(periodic: PeriodicConfig) -> dict[str, Any]:
    return {
        "periodic_dr_asis_scale": periodic.as_is_width_scale,
        "periodic_dr_tr_scale": periodic.transition_width_scale,
        "periodic_kmax_scale": periodic.wavenumber_cutoff_scale,
        "periodic_n_rg": periodic.n_rg,
        "periodic_match_global_kernel_approximations": (
            periodic.match_global_kernel_approximations
        ),
    }


def _flr2_values(run: Flr2Run) -> dict[str, Any]:
    terms = run.terms
    return {
        "flr2_electron_flr": terms.electron_flr,
        "flr2_ion_flr": terms.ion_flr,
        "flr2_electron_potential": terms.electron_potential,
        "flr2_ion_potential": terms.ion_potential,
        "flr2_electron_current": terms.electron_current,
        "flr2_ion_current": terms.ion_current,
        "flr2_include_potential_in_current": terms.include_potential_in_current,
    }


def _render_group(name: str, values: Mapping[str, Any]) -> str:
    lines = [f"&{name}\n"]
    lines.extend(f"    {key} = {_format_value(value)}\n" for key, value in values.items())
    lines.append("/\n\n")
    return "".join(lines)


def _format_value(value: Any) -> str:
    if isinstance(value, bool):
        return ".true." if value else ".false."
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    if isinstance(value, (list, tuple)):
        return ", ".join(_format_value(item) for item in value)
    return repr(value)


def _lower_keys(values: Mapping[str, Any]) -> dict[str, Any]:
    return {str(key).lower(): value for key, value in values.items()}


def _validate_contract(groups: Mapping[str, Mapping[str, Any]]) -> None:
    missing = [name.upper() for name in _MANDATORY_GROUPS if name not in groups]
    if missing:
        raise ConfigurationError(f"missing required namelist group(s): {', '.join(missing)}")

    unknown_groups = set(groups) - set(_SUPPORTED_KEYS)
    if unknown_groups:
        names = ", ".join(sorted(name.upper() for name in unknown_groups))
        raise ConfigurationError(f"unsupported namelist group(s): {names}")

    for group, values in groups.items():
        unknown = set(values) - _SUPPORTED_KEYS[group]
        if unknown:
            names = ", ".join(sorted(unknown))
            raise ConfigurationError(f"unsupported key(s) in {group.upper()}: {names}")

    io = groups["kim_io"]
    if io.get("hdf5_input") is not False:
        raise ConfigurationError("KIM_IO.hdf5_input must be .false.")
    if io.get("hdf5_output") is not True:
        raise ConfigurationError("KIM_IO.hdf5_output must be .true.")


def _from_groups(groups: Mapping[str, Mapping[str, Any]]) -> SimulationConfig:
    config_values = groups["kim_config"]
    io_values = groups["kim_io"]
    setup_values = groups["kim_setup"]
    grid_values = groups["kim_grid"]
    profile_values = groups["kim_profiles"]
    run_type = _required(config_values, "type_of_run")
    allowed_optional_groups = {
        "electrostatic": set(),
        "electrostatic_periodic": {"kim_periodic"},
        "flr2": {"kim_flr2"},
    }.get(run_type, set())
    present_run_groups = set(groups) & {"kim_periodic", "kim_flr2"}
    invalid_run_groups = present_run_groups - allowed_optional_groups
    if invalid_run_groups:
        names = ", ".join(sorted(name.upper() for name in invalid_run_groups))
        raise ConfigurationError(f"{names} is not valid for run type {run_type!r}")

    plasma = _parse_plasma(groups, config_values)
    physics = PhysicsConfig(
        collision_model=_required(config_values, "collision_model"),
        ion_collision_model=config_values.get("ion_collision_model", "FokkerPlanck"),
        collisionless_kpar_epsilon=_optional_positive(
            config_values.get("collisionless_kpar_epsilon")
        ),
        ion_fp_collision_scale=config_values.get("ion_fp_collision_scale", 1.0),
        collision_frequency_scale=config_values.get("collision_frequency_scale", 1.0),
        density_scale=(
            _required(config_values, "number_density_rescale")
            if config_values.get("rescale_density", False)
            else None
        ),
        ion_larmor_radius_scale=config_values.get("ion_flr_scale_factor", 1.0),
        artificial_debye_case=_required(config_values, "artificial_debye_case"),
        conserve_energy=config_values.get("boole_energy_conservation", True),
        turn_off_ions=_required(config_values, "turn_off_ions"),
        turn_off_electrons=_required(config_values, "turn_off_electrons"),
    )
    setup = SetupConfig(
        btor=_required(setup_values, "btor"),
        major_radius=_required(setup_values, "r0"),
        m_mode=_required(setup_values, "m_mode"),
        n_mode=_required(setup_values, "n_mode"),
        frequency=_required(setup_values, "omega"),
        br_boundary_real=_required(setup_values, "br_boundary_re"),
        br_boundary_imag=_required(setup_values, "br_boundary_im"),
        spline_base=_required(setup_values, "spline_base"),
        magnetic_perturbation_type=_required(setup_values, "type_br_field"),
        collisions_off=_required(setup_values, "collisions_off"),
        constant_profile_mode=_required(setup_values, "set_profiles_constant"),
        boundary_condition=_required(setup_values, "bc_type"),
        cyclotron_harmonics=_required(setup_values, "mphi_max"),
    )
    grid = GridConfig(
        radial_minimum=_required(grid_values, "r_min"),
        plasma_radius=_required(grid_values, "r_plas"),
        resonance_width=_required(grid_values, "width_res"),
        resonance_amplification=_required(grid_values, "ampl_res"),
        maximum_step_scale=_required(grid_values, "hrmax_scaling"),
        l_space_dim=_required(grid_values, "l_space_dim"),
        rg_space_dim=_required(grid_values, "rg_space_dim"),
        rg_spacing=_required(grid_values, "grid_spacing_rg"),
        l_spacing=_required(grid_values, "grid_spacing_xl"),
        theta_integration=_required(grid_values, "theta_integration"),
        larmor_skip_factor=_required(grid_values, "larmor_skip_factor"),
        gauss_nodes_x=_required(grid_values, "gauss_int_nodes_nx"),
        gauss_nodes_x_prime=_required(grid_values, "gauss_int_nodes_nxp"),
        gauss_nodes_theta=_required(grid_values, "gauss_int_nodes_ntheta"),
        rkf45_absolute_tolerance=_required(grid_values, "rkf45_atol"),
        rkf45_relative_tolerance=_required(grid_values, "rkf45_rtol"),
        kernel_taper_skip_threshold=_required(grid_values, "kernel_taper_skip_threshold"),
        quadpack_algorithm=_required(grid_values, "quadpack_algorithm"),
        quadpack_key=_required(grid_values, "quadpack_key"),
        quadpack_limit=_required(grid_values, "quadpack_limit"),
        quadpack_absolute_tolerance=_required(grid_values, "quadpack_epsabs"),
        quadpack_relative_tolerance=_required(grid_values, "quadpack_epsrel"),
        quadpack_use_u_substitution=_required(grid_values, "quadpack_use_u_substitution"),
    )
    profile_location = Path(_required(io_values, "profile_location"))
    input_profile_directory = Path(_required(profile_values, "input_profile_dir"))
    if profile_location != input_profile_directory:
        raise ConfigurationError(
            "KIM_IO.profile_location and KIM_PROFILES.input_profile_dir "
            "profile directories must match"
        )
    profiles = ProfileConfig(
        directory=profile_location,
        coordinate_type=_required(profile_values, "coord_type"),
        density_file=_required(profile_values, "n_file"),
        electron_temperature_file=_required(profile_values, "te_file"),
        ion_temperature_file=_required(profile_values, "ti_file"),
        toroidal_velocity_file=_required(profile_values, "vz_file"),
        radial_electric_field_file=_required(profile_values, "er_file"),
        safety_factor_file=_required(profile_values, "q_file"),
    )
    io = IOConfig(
        hdf5_input=_required(io_values, "hdf5_input"),
        hdf5_output=_required(io_values, "hdf5_output"),
        log_level=_required(io_values, "log_level"),
        data_verbosity=_required(io_values, "data_verbosity"),
        calculate_asymptotics=_required(io_values, "calculate_asymptotics"),
        write_diagnostics_dat=_required(io_values, "write_diagnostics_dat"),
    )
    run: dict[str, Any] = {"run_type": run_type}
    if run_type == "electrostatic_periodic":
        values = groups.get("kim_periodic")
        if values is None:
            raise ConfigurationError("missing required namelist group: KIM_PERIODIC")
        run["periodic"] = _parse_periodic(values)
    elif run_type == "flr2":
        values = groups.get("kim_flr2")
        if values is None:
            raise ConfigurationError("missing required namelist group: KIM_FLR2")
        run["terms"] = _parse_flr2(values)

    return SimulationConfig.model_validate(
        {
            "run": run,
            "plasma": plasma,
            "physics": physics,
            "setup": setup,
            "grid": grid,
            "profiles": profiles,
            "io": io,
        }
    )


def _parse_plasma(
    groups: Mapping[str, Mapping[str, Any]], config: Mapping[str, Any]
) -> BuiltinPlasma | ExplicitPlasma:
    count = _required(config, "number_of_ion_species")
    if not config.get("read_species_from_namelist", False):
        if "kim_species" in groups:
            raise ConfigurationError("KIM_SPECIES is not valid for built-in plasma")
        if count != 1:
            raise ConfigurationError("built-in plasma requires number_of_ion_species = 1")
        return BuiltinPlasma(isotope=_required(config, "plasma_type"))

    species = groups.get("kim_species")
    if species is None:
        raise ConfigurationError("missing required namelist group: KIM_SPECIES")
    masses = _as_list(_required(species, "ai"))
    charges = _as_list(_required(species, "zi"))
    if len(masses) != count or len(charges) != count:
        raise ConfigurationError("KIM_SPECIES arrays must match number_of_ion_species")
    return ExplicitPlasma(
        ions=tuple(
            IonSpecies(mass_number=mass, charge_number=charge)
            for mass, charge in zip(masses, charges, strict=True)
        )
    )


def _parse_periodic(values: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "as_is_width_scale": _required(values, "periodic_dr_asis_scale"),
        "transition_width_scale": _required(values, "periodic_dr_tr_scale"),
        "wavenumber_cutoff_scale": _required(values, "periodic_kmax_scale"),
        "n_rg": _required(values, "periodic_n_rg"),
        "match_global_kernel_approximations": _required(
            values, "periodic_match_global_kernel_approximations"
        ),
    }


def _parse_flr2(values: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "electron_flr": _required(values, "flr2_electron_flr"),
        "ion_flr": _required(values, "flr2_ion_flr"),
        "electron_potential": _required(values, "flr2_electron_potential"),
        "ion_potential": _required(values, "flr2_ion_potential"),
        "electron_current": _required(values, "flr2_electron_current"),
        "ion_current": _required(values, "flr2_ion_current"),
        "include_potential_in_current": _required(values, "flr2_include_potential_in_current"),
    }


def _required(values: Mapping[str, Any], key: str) -> Any:
    if key not in values:
        raise ConfigurationError(f"missing required namelist key: {key}")
    return values[key]


def _optional_positive(value: Any) -> Any:
    return value if value is not None and value > 0 else None


def _as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else [value]
