"""Preparation of explicit experimental profiles for a KIM case."""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence

import numpy as np
from kim.config import ProfileConfig, SimulationConfig
from kim.conventions import SourceMetadata, convert_quantity
from kim.errors import ExperimentalInputError
from kim.importers.experimental import MarsFInput
from numpy.typing import NDArray


@dataclass(frozen=True)
class PreparedExperimentalCase:
    """Files and validated request produced by experimental preparation."""

    directory: Path
    profiles: Path
    equilibrium: Path
    request: Path
    report: Path
    config: SimulationConfig


def prepare_marsf_case(
    source: MarsFInput,
    config: SimulationConfig,
    destination: Path | str,
    *,
    equilibrium_file: Path | str | None = None,
    equilibrium_executable: Path | str | None = None,
    equilibrium_input_files: Sequence[Path | str] = (),
    equilibrium_timeout_seconds: float = 3600.0,
) -> PreparedExperimentalCase:
    """Stage a MARS-F source as a runnable, provenance-preserving KIM case.

    The equilibrium table must either be supplied directly or generated by an
    explicitly supplied executable.  The executable is run without a shell in
    a fresh staging directory; input files are copied there before launch.
    """

    if not isinstance(source, MarsFInput):
        raise ExperimentalInputError("source must be a MarsFInput instance")
    if not isinstance(config, SimulationConfig):
        raise ExperimentalInputError("config must be a SimulationConfig instance")
    if equilibrium_file is not None and equilibrium_executable is not None:
        raise ExperimentalInputError("provide equilibrium_file or equilibrium_executable, not both")
    if equilibrium_file is None and equilibrium_executable is None:
        raise ExperimentalInputError(
            "an explicit equilibrium_file or equilibrium_executable is required"
        )
    if not np.isfinite(equilibrium_timeout_seconds) or equilibrium_timeout_seconds <= 0.0:
        raise ExperimentalInputError("equilibrium_timeout_seconds must be positive and finite")

    final_directory = Path(destination).absolute()
    if final_directory.exists() or final_directory.is_symlink():
        raise ExperimentalInputError(f"prepared case already exists: {final_directory}")
    final_directory.parent.mkdir(parents=True, exist_ok=True)

    staging_directory = Path(
        tempfile.mkdtemp(prefix=f".{final_directory.name}-", dir=final_directory.parent)
    )
    try:
        prepared = _prepare_in_directory(
            source,
            config,
            staging_directory,
            equilibrium_file=equilibrium_file,
            equilibrium_executable=equilibrium_executable,
            equilibrium_input_files=equilibrium_input_files,
            equilibrium_timeout_seconds=equilibrium_timeout_seconds,
            final_directory=final_directory,
        )
        _commit_staging_directory(staging_directory, final_directory)
    except Exception:
        shutil.rmtree(staging_directory, ignore_errors=True)
        raise

    return PreparedExperimentalCase(
        directory=final_directory,
        profiles=final_directory / "profiles",
        equilibrium=final_directory / "equilibrium" / prepared.equilibrium.name,
        request=final_directory / "request.json",
        report=final_directory / "conversion_report.json",
        config=prepared.config,
    )


def _commit_staging_directory(staging: Path, destination: Path) -> None:
    try:
        destination.mkdir()
    except FileExistsError as error:
        raise ExperimentalInputError(f"prepared case already exists: {destination}") from error
    try:
        for child in staging.iterdir():
            target = destination / child.name
            if target.exists() or target.is_symlink():
                raise ExperimentalInputError(f"prepared case target already exists: {target}")
            child.rename(target)
        staging.rmdir()
    except Exception:
        shutil.rmtree(destination, ignore_errors=True)
        raise


def _prepare_in_directory(
    source: MarsFInput,
    config: SimulationConfig,
    directory: Path,
    *,
    equilibrium_file: Path | str | None,
    equilibrium_executable: Path | str | None,
    equilibrium_input_files: Sequence[Path | str],
    equilibrium_timeout_seconds: float,
    final_directory: Path,
) -> PreparedExperimentalCase:
    source_directory = directory / "source"
    equilibrium_directory = directory / "equilibrium"
    profiles_directory = directory / "profiles"
    source_directory.mkdir()
    equilibrium_directory.mkdir()
    profiles_directory.mkdir()

    source_hashes: dict[str, str] = {}
    for _name, source_path in source.source_files.items():
        target = source_directory / source_path.name
        shutil.copy2(source_path, target)
        source_hashes[f"source/{source_path.name}"] = _sha256(source_path)
    (source_directory / "metadata.json").write_text(
        json.dumps(source.metadata.model_dump(mode="json"), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    generated = equilibrium_file is None
    generator_provenance: dict[str, object] | None = None
    if generated:
        assert equilibrium_executable is not None
        input_names: set[str] = set()
        for input_file in equilibrium_input_files:
            input_path = Path(input_file)
            if not input_path.is_file():
                raise ExperimentalInputError(f"equilibrium input file does not exist: {input_path}")
            if input_path.name in input_names:
                raise ExperimentalInputError(
                    f"duplicate equilibrium input basename: {input_path.name}"
                )
            input_names.add(input_path.name)
            shutil.copy2(input_path, equilibrium_directory / input_path.name)
            source_hashes[f"equilibrium_input/{input_path.name}"] = _sha256(input_path)
        generator_command = _resolve_generator_command(equilibrium_executable)
        _run_equilibrium_generator(
            generator_command, equilibrium_directory, equilibrium_timeout_seconds
        )
        generator_path = _resolved_executable_path(generator_command[0])
        command_file_hashes = {
            str(Path(part)): _sha256(Path(part))
            for part in generator_command
            if Path(part).is_file()
        }
        generator_provenance = {
            "command": generator_command,
            "executable": str(generator_path) if generator_path else generator_command[0],
            "sha256": _sha256(generator_path) if generator_path else None,
            "command_file_hashes": command_file_hashes,
            "timeout_seconds": equilibrium_timeout_seconds,
        }
        equilibrium_source = equilibrium_directory / "equil_r_q_psi.dat"
        if equilibrium_source.is_symlink() or not equilibrium_source.is_file():
            raise ExperimentalInputError(
                "equilibrium executable must write a regular equil_r_q_psi.dat file"
            )
        equilibrium_operation = "generated by supplied equilibrium executable"
    else:
        equilibrium_source = Path(equilibrium_file).absolute()
        if not equilibrium_source.is_file():
            raise ExperimentalInputError(f"equilibrium file does not exist: {equilibrium_source}")
        staged_equilibrium = equilibrium_directory / equilibrium_source.name
        shutil.copy2(equilibrium_source, staged_equilibrium)
        equilibrium_source = staged_equilibrium
        equilibrium_operation = "copied from explicit equilibrium_file"

    equilibrium_hash_name = equilibrium_source.name
    source_hashes[f"equilibrium/{equilibrium_hash_name}"] = _sha256(equilibrium_source)
    radius, q, psi_n = _read_equilibrium(equilibrium_source)
    output_grid, profile_values, coordinate_operation = _prepare_profiles(
        source, radius, q, psi_n, profiles_directory, config.profiles
    )
    _validate_radial_coverage(config, output_grid)
    q_values = (
        q if source.metadata.coordinate == "sqrt_psiN" else _interpolate(q, radius, output_grid)
    )
    _write_profile(profiles_directory / config.profiles.safety_factor_file, output_grid, q_values)

    prepared_config = config.model_copy(
        update={
            "profiles": config.profiles.model_copy(
                update={"directory": final_directory / "profiles"}
            )
        }
    )
    request_payload = prepared_config.model_dump(mode="json")
    request_payload["profiles"]["directory"] = "./profiles"
    request_path = directory / "request.json"
    request_path.write_text(
        json.dumps(request_payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    report = {
        "schema_version": 1,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "source": source.metadata.model_dump(mode="json"),
        "target": "KIM-CGS-r_eff",
        "equilibrium": {
            "source": str(Path(equilibrium_file).absolute()) if equilibrium_file else None,
            "staged_file": f"equilibrium/{equilibrium_source.name}",
            "operation": equilibrium_operation,
        },
        "generator": generator_provenance,
        "coordinate_operation": coordinate_operation,
        "source_hashes": source_hashes,
        "operations": _unit_operations(source),
        "output_grid_points": int(output_grid.size),
    }
    report_path = directory / "conversion_report.json"
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return PreparedExperimentalCase(
        directory=directory,
        profiles=profiles_directory,
        equilibrium=equilibrium_source,
        request=request_path,
        report=report_path,
        config=prepared_config,
    )


def _run_equilibrium_generator(
    command: Sequence[str], working_directory: Path, timeout_seconds: float
) -> None:
    if not command:
        raise ExperimentalInputError("equilibrium_executable must not be empty")
    try:
        completed = subprocess.run(
            command,
            cwd=working_directory,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
        )
    except subprocess.TimeoutExpired as error:
        raise ExperimentalInputError(
            f"equilibrium generator timed out after {timeout_seconds:g} seconds"
        ) from error
    except OSError as error:
        raise ExperimentalInputError(
            f"unable to execute equilibrium generator: {command[0]}"
        ) from error
    if completed.returncode != 0:
        details = completed.stderr.strip() or completed.stdout.strip()
        raise ExperimentalInputError(
            f"equilibrium generator failed with exit code {completed.returncode}: {details}"
        )
    (working_directory / "generator.stdout").write_text(completed.stdout, encoding="utf-8")
    (working_directory / "generator.stderr").write_text(completed.stderr, encoding="utf-8")


def _resolve_generator_command(executable: Path | str) -> list[str]:
    candidate = Path(executable).expanduser()
    if candidate.is_absolute():
        return [str(candidate)]
    if (
        (Path.cwd() / candidate).is_file()
        or os.sep in str(candidate)
        or (os.altsep and os.altsep in str(candidate))
    ):
        return [str((Path.cwd() / candidate).resolve())]
    return [str(executable)]


def _resolved_executable_path(command: str) -> Path | None:
    candidate = Path(command)
    if candidate.is_file():
        return candidate.absolute()
    located = shutil.which(command)
    return Path(located).absolute() if located else None


def _read_equilibrium(
    path: Path,
) -> tuple[NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]]:
    rows: list[tuple[float, float, float]] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        columns = stripped.split()
        if len(columns) < 3:
            raise ExperimentalInputError(f"{path}: row {line_number} needs r_eff, q, and psi")
        try:
            row = tuple(float(value.replace("D", "E").replace("d", "e")) for value in columns[:3])
        except ValueError as error:
            raise ExperimentalInputError(f"{path}: row {line_number} is not numeric") from error
        if not np.all(np.isfinite(row)):
            raise ExperimentalInputError(f"{path}: row {line_number} contains non-finite values")
        rows.append(row)
    if len(rows) < 2:
        raise ExperimentalInputError(f"{path}: equilibrium table needs at least two rows")
    data = np.asarray(rows, dtype=np.float64)
    if np.any(np.diff(data[:, 0]) <= 0):
        raise ExperimentalInputError(f"{path}: radius column must be strictly increasing")
    if data[-1, 2] == 0:
        raise ExperimentalInputError(f"{path}: final psi value must not be zero")
    psi_n = data[:, 2] / data[-1, 2]
    if np.any(np.diff(psi_n) <= 0):
        raise ExperimentalInputError(f"{path}: normalized psi column must be strictly increasing")
    return data[:, 0], data[:, 1], psi_n


def _prepare_profiles(
    source: MarsFInput,
    radius: NDArray[np.float64],
    q: NDArray[np.float64],
    psi_n: NDArray[np.float64],
    profiles_directory: Path,
    profile_config: ProfileConfig,
) -> tuple[NDArray[np.float64], dict[str, NDArray[np.float64]], str]:
    source_metadata = _conversion_metadata(source)
    if source.metadata.coordinate == "sqrt_psiN":
        output_grid = radius
        coordinate = psi_n
        coordinate_operation = "natural cubic interpolation from sqrt_psiN to equilibrium r_eff"
        for profile in source.profiles.values():
            if profile.coordinate[0] < 0.0 or profile.coordinate[-1] > 1.0:
                raise ExperimentalInputError(
                    "sqrt_psiN coordinate must be within the declared [0, 1] domain"
                )
        profile_values = {
            name: _convert_profile(
                _interpolate(profile.values, profile.coordinate**2, coordinate),
                name,
                source_metadata,
            )
            for name, profile in source.profiles.items()
        }
        for profile in source.profiles.values():
            _require_covered(profile.coordinate**2, coordinate, "sqrt_psiN profile")
    else:
        scale = 100.0 if source.metadata.coordinate_unit == "m" else 1.0
        output_grid = source.profiles["density"].coordinate * scale
        coordinate_operation = (
            "converted explicit r_eff grid from m to cm"
            if scale != 1.0
            else "preserved explicit r_eff grid"
        )
        for profile in source.profiles.values():
            if not np.array_equal(profile.coordinate, source.profiles["density"].coordinate):
                raise ExperimentalInputError("r_eff MARS-F profiles must share one coordinate grid")
        _require_covered(radius, output_grid, "r_eff profile")
        profile_values = {
            name: _convert_profile(profile.values, name, source_metadata)
            for name, profile in source.profiles.items()
        }
    _validate_profile_filenames(profile_config)
    for name, values in profile_values.items():
        _write_profile(
            profiles_directory / _profile_filename(name, profile_config), output_grid, values
        )
    return output_grid, profile_values, coordinate_operation


def _validate_radial_coverage(config: SimulationConfig, output_grid: NDArray[np.float64]) -> None:
    if output_grid[0] > config.grid.radial_minimum or output_grid[-1] < config.grid.plasma_radius:
        raise ExperimentalInputError(
            "prepared profile grid does not cover the configured radial minimum and plasma radius"
        )


def _conversion_metadata(source: MarsFInput) -> SourceMetadata:
    metadata = source.metadata
    if metadata.electron_temperature_unit != "eV" or metadata.ion_temperature_unit != "eV":
        raise ExperimentalInputError(
            "only eV electron and ion temperatures are approved for KIM preparation"
        )
    return SourceMetadata(
        source=metadata.source,
        coordinate="r_eff",
        radius_unit="cm",
        density_unit=metadata.density_unit,
        temperature_unit="eV",
        magnetic_field_unit="G",
        magnetic_field_sign="preserve",
        electric_field_unit="statV/cm",
        velocity_unit=metadata.toroidal_velocity_unit,
        frequency_unit="rad/s",
        frequency_convention="signed_omega",
        time_phase="exp(-i omega t)",
        perturbation_phase="preserve",
        equilibrium_provenance=metadata.equilibrium_provenance,
        q_unit="1",
        mode_convention="signed",
        fourier_phase="exp(+i k r)",
        complex_phase="preserve",
        resonance_convention="q=-m/n",
    )


def _convert_profile(
    values: NDArray[np.float64], name: str, metadata: SourceMetadata
) -> NDArray[np.float64]:
    quantity = {
        "density": "density",
        "electron_temperature": "temperature",
        "ion_temperature": "temperature",
        "toroidal_velocity": "toroidal_velocity",
    }[name]
    return convert_quantity(values, quantity, metadata)


def _unit_operations(source: MarsFInput) -> list[dict[str, object]]:
    metadata = source.metadata
    operations: list[dict[str, object]] = []
    if metadata.coordinate == "r_eff":
        operations.append(
            {
                "quantity": "radius",
                "source_unit": metadata.coordinate_unit,
                "target_unit": "cm",
                "factor": 100.0 if metadata.coordinate_unit == "m" else 1.0,
            }
        )
    if metadata.density_unit in {"1/m^3", "m^-3"}:
        operations.append(
            {
                "quantity": "density",
                "source_unit": metadata.density_unit,
                "target_unit": "1/cm^3",
                "factor": 1.0e-6,
            }
        )
    else:
        operations.append(
            {
                "quantity": "density",
                "source_unit": metadata.density_unit,
                "target_unit": "1/cm^3",
                "factor": 1.0,
            }
        )
    velocity_factor = 100.0 if metadata.toroidal_velocity_unit == "m/s" else 1.0
    operations.append(
        {
            "quantity": "toroidal_velocity",
            "source_unit": metadata.toroidal_velocity_unit,
            "target_unit": "cm/s",
            "factor": velocity_factor,
        }
    )
    for name, unit in (
        ("electron_temperature", metadata.electron_temperature_unit),
        ("ion_temperature", metadata.ion_temperature_unit),
    ):
        operations.append(
            {"quantity": name, "source_unit": unit, "target_unit": "eV", "factor": 1.0}
        )
    return operations


def _require_covered(
    source_grid: NDArray[np.float64], target_grid: NDArray[np.float64], label: str
) -> None:
    tolerance = 1.0e-12
    if target_grid[0] < source_grid[0] - tolerance or target_grid[-1] > source_grid[-1] + tolerance:
        raise ExperimentalInputError(f"{label} range is outside equilibrium/profile range")


def _interpolate(
    values: NDArray[np.float64],
    source_grid: NDArray[np.float64],
    target_grid: NDArray[np.float64],
) -> NDArray[np.float64]:
    _require_covered(source_grid, target_grid, "profile")
    if source_grid.size == 2:
        return np.interp(target_grid, source_grid, values)
    h = np.diff(source_grid)
    alpha = 3.0 * ((values[2:] - values[1:-1]) / h[1:] - (values[1:-1] - values[:-2]) / h[:-1])
    diagonal = np.ones(source_grid.size)
    upper = np.zeros(source_grid.size - 1)
    lower = np.zeros(source_grid.size - 1)
    rhs = np.zeros(source_grid.size)
    for index in range(1, source_grid.size - 1):
        lower[index - 1] = h[index - 1]
        diagonal[index] = 2.0 * (h[index - 1] + h[index])
        upper[index] = h[index]
        rhs[index] = alpha[index - 1]
    for index in range(1, source_grid.size):
        factor = lower[index - 1] / diagonal[index - 1]
        diagonal[index] -= factor * upper[index - 1]
        rhs[index] -= factor * rhs[index - 1]
    curvature = np.zeros(source_grid.size)
    for index in range(source_grid.size - 2, -1, -1):
        curvature[index] = (rhs[index] - upper[index] * curvature[index + 1]) / diagonal[index]
    evaluation_grid = np.clip(target_grid, source_grid[0], source_grid[-1])
    interval = np.searchsorted(source_grid, evaluation_grid, side="right") - 1
    interval = np.clip(interval, 0, source_grid.size - 2)
    distance = evaluation_grid - source_grid[interval]
    slope = (values[interval + 1] - values[interval]) / h[interval] - h[interval] * (
        curvature[interval + 1] + 2.0 * curvature[interval]
    ) / 3.0
    return (
        values[interval]
        + slope * distance
        + curvature[interval] * distance**2
        + (curvature[interval + 1] - curvature[interval]) * distance**3 / (3.0 * h[interval])
    )


def _write_profile(
    path: Path, coordinate: NDArray[np.float64], values: NDArray[np.float64]
) -> None:
    np.savetxt(path, np.column_stack((coordinate, values)), fmt="%.15e")


def _profile_filename(name: str, config: ProfileConfig) -> str:
    return {
        "density": config.density_file,
        "electron_temperature": config.electron_temperature_file,
        "ion_temperature": config.ion_temperature_file,
        "toroidal_velocity": config.toroidal_velocity_file,
    }[name]


def _validate_profile_filenames(config: ProfileConfig) -> None:
    filenames = (
        config.density_file,
        config.electron_temperature_file,
        config.ion_temperature_file,
        config.toroidal_velocity_file,
        config.radial_electric_field_file,
        config.safety_factor_file,
    )
    if len(set(filenames)) != len(filenames):
        raise ExperimentalInputError("profile filenames must be unique")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


__all__ = ["PreparedExperimentalCase", "prepare_marsf_case"]
