f2py -c src/getIfunc.f90 src/W2_arr.f90 ../../KiLCA/flre/conductivity/calc_Imn_array.f90 -m susc_funcs \
	-llapack \
	-lblas \
	-lkilca  \
	-L../../../libs/sundials/build/src/cvode/ -lsundials_cvode \
	-L../../../libs/sundials/build/src/nvector/serial/ -lsundials_nvecserial \
	-L../../../libs/slatec/ -lslatec \
	-L../../../bessel/lib/ -lbessel \
	-lgsl \
	-lgslcblas \
	-lm \
	-lc
