&antenna
  ra = 0.1
  wa = 500.0
  I0 = 1.0e20
  flab = (1.0e3, 0.0)
  dma = 2
  flag_debug_ant = 0
  flag_eigmode = 1
  modes = 1, 1, 2, -1
/

&background
  rtor = 170.0
  rp = 169.9
  B0 = 100.0
/

&output
  flag_background = 1
/

&eigenmode
  search_flag = 1
  eps_res = 1.0e-15
/
