      SUBROUTINE CROOT(IR,IW,EVEN,RMIN,RMAX,CEN,NROOT,
     +                 ZROOT,FAIL)
C
C
C     AUTHORS: L.C. BOTTEN, M.S. CRAIG AND R.C.MCPHEDRAN(*)
C
C              SCHOOL OF MATHEMATICAL SCIENCES,
C              THE NEW SOUTH WALES INSTITUTE OF TECHNOLOGY,
C              P.O. BOX 123, BROADWAY,
C              N.S.W. 2007, AUSTRALIA.
C
C          (*) SIR FRANK PACKER THEORETICAL DEPARTMENT,
C              SCHOOL OF PHYSICS,
C              THE UNIVERSITY OF SYDNEY,
C              N.S.W. 2006, AUSTRALIA.
C
C    'CROOT' IS THE MAIN ENTRY TO THE SUITE OF ZERO FINDING
C  ROUTINES.  ROOTS ARE EXTRACTED WITHIN AN ANNULAR REGION
C  IN THE COMPLEX PLANE CENTRED ON 'CEN', OF INNER AND OUTER
C  RADII 'RMIN' AND 'RMAX' RESPECTIVELY.  AFTER THE PROCESS
C  IS COMPLETE, THE 'NROOT' ROOTS ARE STORED IN THE COMPLEX
C  VECTOR 'ZROOT'.  NOTE THAT RMIN CAN BE ZERO.
C
C  'FAIL' IS A LOGICAL VARIABLE SIGNALLING AN UNSUCCESSFUL
C  COMPLETION OF 'CROOT' IF IT IS SET .TRUE..
C
C  'IR' IS THE UNIT NUMBER FROM WHICH DATA IS READ.  IF IT
C  IS SET NEGATIVE THEN THE VARIOUS METHOD PARAMETERS IN THE
C  COMMONS BELOW TAKE DEFAULT VALUES.
C
C  'IW' IS THE UNIT NUMBER TO WHICH A TRACE OF THE OPERATION
C  OF 'CROOT' IS WRITTEN.  IF THIS PARAMETER IS NEGATIVE THEN
C  THE TRACE IS SUPPRESSED.
C
C  'EVEN' IS A LOGICAL VARIABLE SET TRUE IF THE FUNCTION
C  SPECIFIED IN THE SUBROUTINE 'FNDER' HAS EVEN SYMMETRY.
C    I.E. FOR A FUNCTION F, F(Z) = F(-Z)  -  EVEN SYMMETRY
C  FOR ODD SYMMETRY ( F(Z) = -F(-Z) ), THE FUNCTION SHOULD
C  HAVE THE ROOT(S) AT THE ORIGIN EXPLICITLY REMOVED AND
C  THEREAFTER BE TREATED AS EVEN.  THIS IS DONE FOR FASTER
C  EXECUTION.  FOR ALL OTHER CASES THE PARAMETER 'EVEN'
C  SHOULD BE SET .FALSE..
C
C
C  THESE ROUTINES ARE BASED ON THE METHOD OF  :
C  L.M. DELVES AND J.N. LYNESS,
C  MATHS. COMPUT. 21(1967) 543, BUT WITH AN IMPROVED
C  SUBDIVISION  OF THE SEARCH REGION.
C
C**************************************************************

      IMPLICIT DOUBLE PRECISION (A-H,O-Z)

      PARAMETER (MBIS=20, MSIG=10, MTROUB=10)
C
      LOGICAL EVEN,LPRINT,ABRET,FAIL
      INTEGER TCROOT,TESIGR,TESIGT
      DOUBLE COMPLEX CEN,CCEN,ZROOT
C
      DIMENSION ZROOT(*)
C
      EQUIVALENCE (MENTRY,TCROOT)
C
      COMMON /POWER/  IPOWER
      COMMON /METHOD/ CRIT,MAXBIS
      COMMON /ADJRAD/ ADJO,ADJI
      COMMON /ADJANG/ ADJT
      COMMON /RSCALE/ SCALE,CCEN
      COMMON /TOLE/   EP1,EP2
      COMMON /TOLI/   TOLINT,TINT
      COMMON /OUT/    LPRINT,ICW
      COMMON /RADSEP/ RSEP
      COMMON /MDIFF/  TCROOT,TESIGR,TESIGT
C
C
C  /POWER/   'IPOWER' = 1  FOR EVEN FUNCTION
C                       2  OTHERWISE
C
C  /METHOD/  'CRIT' IS AN UPPER BOUND FOR THE MODULUS OF THE
C            FUNCTION TO BE INTEGRATED.  IF IT EXCEEDS THIS
C            NUMBER THEN THE INTEGRATION IS ABORTED AND ANOTHER
C            CONTOUR IS SELECTED.
C            'MAXBIS' IS THE MAXIMUM NUMBER OF BISECTIONS PERMITTED
C            WITHIN THE INTEGRATION ROUTINE 'TRAP', WHICH EMPLOYS
C            THE TRAPEZOIDAL RULE.
C
C  /ADJRAD/  'ADJO' IS THE MULTIPLICATIVE FACTOR BY WHICH THE INITIAL
C            OUTER RADIUS IS CHANGED WHEN A ZERO LIES TOO CLOSE TO THE
C            OUTER CIRCUMFERENCE OF THE ANNULUS.
C            'ADJI' IS THE CORRESPONDING FACTOR FOR THE INNER RADIUS.
C
C  /ADJANG/  'ADJT' IS THE SUBTRACTIVE FACTOR BY WHICH THE
C            ANGLE (IN RADIANS) OF THE INITIAL RAY IS CHANGED
C            WHEN A ZERO LIES TOO CLOSE TO THE INTEGRATION
C            CONTOUR.  THIS IS USED IN THE SECTOR RECURSION
C            ROUTINE 'RECURT'.
C
C  /RSCALE/  FOR PURPOSES OF GENERALITY THE PROGRAM FINDS ZEROS ON
C            A UNIT CIRCLE CENTRED ON THE ORIGIN OF THE (PROGRAM'S)
C            Z PLANE.  'SCALE' AND 'CCEN' DEFINE A MAPPING FROM THE
C            Z(PROG.) PLANE TO THE Z(PHYS.) PLANE ACCORDING TO
C              Z(PHYS.) = CCEN + SCALE * Z(PROG.)
C            IT SHOULD BE NOTED THAT THE USER MUST WRITE A SUBROUTINE
C            WHOSE DECLARATIVE LINE READS:
C               SUBROUTINE FNDER(Z,FZ,DZ)
C               COMPLEX Z,FZ,DZ
C            THE VARIABLE  'Z' IS THE PHYSICAL VARIABLE.  ALSO, 'FZ'
C            AND 'DZ' ARE THE FUNCTION AND DERIVATIVES RESPECTIVELY.
C            THUS, THE USER PROGRAMS IN TERMS OF PHYSICAL PARAMETERS
C            AND NEED NOT BE CONCERNED WITH ANY RESCALING DONE WITHIN
C            THE PROGRAM.
C
C  /TOLE/    'EP1' AND 'EP2' DEFINE TOLERANCES ON THE INDEPENDENT (Z)
C            AND DEPENDENT (F(Z)) VARIABLES FOR THE ITERATIVE ROOT
C            EXTRACTION.  NOTE THAT 'EP1' SHOULD BE GREATER THAN
C            OR EQUAL TO THE RELATIVE PRECISION OF THE COMPUTER
C            BEING USED.  THAT NUMBER (EP) IS THE SMALLEST NUMBER
C            (IN MODULUS) SUCH THAT 1.+EP STILL DIFFERS FROM
C            1.  E.G. FOR A CDC CYBER 70/170 SERIES COMPUTER
C            (60 BIT WORD) THIS IS 1.E-14 AND FOR A HONEYWELL
C            LEVEL 66 SERIES COMPUTER (36 BIT WORD) EP=1.E-8.
C
C  /TOLI/    'TOLINT' IS **********THE TOLERANCE TO WHICH INTEGRALS IN 'TRAP'
C            MUST CONVERGE.
C            'TINT' IS A TOLERANCE ON THE DEPARTURE FROM AN INTEGER
C            OF THE PROGRAM'S ESTIMATE OF THE NUMBER OF ROOTS WITHIN
C            A GIVEN REGION.
C
C  /OUT/     'LPRINT' IS A LOGICAL VARIABLE SPECIFYING WHETHER A
C            TRACE OCCURS ON THE UNIT 'ICW'.
C
C  /RADSEP/  'RSEP' IS A FACTOR SPECIFYING THE LEAST SEPARATION
C            OF ANNULI BEFORE SECTORING IS PERFORMED IN 'RECURT'.
C
C 'NSIG' IS THE NUMBER OF SUMS OF POWERS OF ROOTS THAT ARE GENERATED
C  IN THE PROCESS OF ESTIMATING THE ROOTS.  IT HAS BEEN FOUND THAT
C  NSIG=4 IS A REASONABLE ESTIMATE.  IF 'NSIG' IS LESS THAN 4, THE
C  PROCESS IS TOO SLOW AN**********D IF GREATER THAN 4, THE PROCESS MAY BE
C  UNRELIABLE.  'NSIG' IS IN FACT THE MAXIMUM NUMBER OF ROOTS THAT
C  MAY BE EXTRACTED AT ANY ONE TIME.
C
C
C
      IF (EVEN) THEN
        IPOWER=2
      ELSE
        IPOWER=1
      END IF
C
      IF (IW.LE.0) THEN
        LPRINT=.FALSE.
        ICW=-IW
      ELSE
        LPRINT=.TRUE.
        ICW=IW
      END IF
C
      IF (IR.LE.0) THEN
C       DEFAULT VALUES OF METHOD PARAMETERS
        NSIG  =4
        RSEP  =0.10
        CRIT  =1000.0
        MAXBIS=50 !12
        EP1   =1.E-8 !1.E-8
        EP2   =1.E-12 !1.E-12
        TOLINT=1.E-3  !1.E-3
        TINT  =1.E-2  !1.E-2

    ADJO  =1.05
        ADJI  =0.95
        ADJT  =0.05
        TCROOT=3
        TESIGR=3
        TESIGT=3
      ELSE
C       READ IN LIST DIRECTED FORMAT THE METHOD PARAMETERS
        READ (IR,*) NSIG,RSEP
        NSIG=MIN(ABS(NSIG),MSIG)
        RSEP=MIN(ABS(RSEP),1.D0)
C
        READ (IR,*) MAXBIS,CRIT
        MAXBIS=MIN(ABS(MAXBIS),MBIS)
        CRIT=ABS(CRIT)
C
        READ (IR,*) EP1,EP2
        EP1=ABS(EP1)
        EP2=ABS(EP2)
C
        READ (IR,*) TOLINT,TINT
        TOLINT=ABS(TOLINT)
        TINT=ABS(TINT)
C
        READ (IR,*) ADJO,ADJI,ADJT
        ADJO=ABS(ADJO)
        ADJI=ABS(ADJI)
C
        READ (IR,*) TCROOT,TESIGR,TESIGT
        TCROOT=MIN(ABS(TCROOT),MTROUB)
        TESIGR=MIN(ABS(TESIGR),MTROUB)
        TESIGT=MIN(ABS(TESIGT),MTROUB)
C
      END IF
C
C
      IENTRY=0
      NROOT=0
      RRMIN=RMIN/RMAX
      SCALE=RMAX
      RRMAX=1.0
      CCEN=CEN
C
C     PRINT OUT THE METHOD PARAMETER SETTINGS
      IF (LPRINT) THEN
        CENR=REAL(CEN)
        CENI=AIMAG(CEN)
        WRITE (IW,5) RMIN,RMAX,EVEN,CENR,CENI,NSIG,RSEP,
     +               MAXBIS,CRIT,TOLINT,TINT,EP1,EP2,
     +               ADJO,ADJI,ADJT,TCROOT,TESIGR,TESIGT
    5   FORMAT(//1X,'CROOT  - ENTRY - METHOD PARAMETERS ARE:'/
     +          1X,'RMIN  =',1PE12.5,T25,'RMAX  =',1PE12.5,
     +             T49,'EVEN  =',L2/
     +          1X,'CENTRE=',1P2E12.5/
     +          1X,'NSIG  =',I2,T25,'RSEP  =',1PE12.5/
     +          1X,'MAXBIS=',I2,T25,'CRIT  =',1PE12.5/
     +          1X,'TOLINT=',1PE12.5,T25,'TINT  =',1PE12.5/
     +          1X,'EP1   =',1PE12.5,T25,'EP2   =',1PE12.5/
     +          1X,'ADJO  =',1PE12.5,T25,'ADJI  =',1PE12.5,
     +             T49,'ADJT  =',1PE12.5/
     +          1X,'TCROOT=',I2,T25,'TESIGR=',I2,T49,'TESIGT=',I2)
      END IF
      TOLINT=TOLINT*10.
C
C
C     REPEAT
   10 CONTINUE
        IENTRY=IENTRY+1
        TOLINT=TOLINT/10.
        IF (LPRINT) WRITE (ICW,20) IENTRY,TOLINT
   20   FORMAT(//1X,'CROOT  - ON ENTRY ',I2,' INTO RECUR, TOLINT=',
     +         1PE12.5)
C
        CALL RECUR(NSIG,RRMIN,RRMAX,ABRET,FAIL,NROOT,ZROOT)
C
      IF (.NOT.FAIL .AND. ABRET.AND.(IENTRY.LT.MENTRY)) GOTO 10
C     UNTIL ((.NOT.ABRET).OR.(IENTRY.GE.MENTRY))
C
C
      IF (ABRET) THEN
        FAIL=.TRUE.
        WRITE (ICW,50)
   50   FORMAT(1X,'CROOT  - TOO MUCH TROUBLE - GIVEN UP')
      ELSE
        FAIL=.FALSE.
        IF (LPRINT) WRITE (ICW,60)
   60   FORMAT(1X,'CROOT  - SUCCESSFUL COMPLETION'//)
      END IF
C
      RETURN
      END
      SUBROUTINE RECUR(NSIG,RMIN,RMAX,ABRET,FAIL,NR,ZR)
C
C    THE PROCESS OF FINDING ZEROES OF ANALYTIC FUNCTIONS USING
C  THIS METHOD IS RECURSIVE.  'RECUR' IS THE RECURSION DRIVER
C  FOR THE WHOLE SUITE OF SUBROUTINES.  IT CONTROLS THE CHOICE
C  OF ANNULAR REGIONS IN WHICH ROOTS ARE TO BE LOCATED AND AS
C  SUCH REQUIRES THE USE OF TWO STACKS.  THESE ARE 'SR' FOR THE
C  RADII OF CIRCLES AND 'SSR' FOR THE SUMS OF POWERS OF ROOTS.
C  SHOULD ANY TWO CIRCLES BE TOO CLOSE, THEN RADIAL RECURSION
C  IS HALTED AND ANGULAR RECURSION (CONTROLLED BY 'RECURT') IS
C  PERFORMED UNTIL THE ROOTS WITHIN THE ANNULUS ARE CALCULATED.
C
C  'NSIG' IS THE NUMBER OF ROOTS THAT MAY BE EXTRACTED AT ANY TIME.
C  IF THE NUMBER OF ROOTS WITHIN A GIVEN ANNULUS EXCEEDS 'NSIG',
C  THEN THE ANNULUS IS BISECTED AND THE PROCESS CONTINUES IN
C  A RECURSIVE MANNER.  SEE ALSO THE COMMENTS REGARDING 'NSIG'
C  IN THE MAIN DRIVER 'CROOT'.
C
C  'RMIN' AND 'RMAX' ARE THE SCALED RADII (ON A UNIT CIRCLE) OF THE
C  INNER AND OUTER CIRCLES BETWEEN WHICH THE ROOTS ARE TO BE FOUND.
C
C  'ABRET' IS A LOGICAL VARIABLE SIGNALLING AN ABNORMAL RETURN.
C  THIS GENERALLY MEANS THAT THE INTEGRATION TOLERANCES NEED
C  TIGHTENING WITHIN 'CROOT'.
C
C  ON THE OTHER HAND, 'FAIL' SIGNALS THAT SOMETHING FATAL HAS
C  OCCURRED WITHIN THE PROGRAM AND RECOVERY IS IMPOSSIBLE.
C
C  WHEN 'RECUR' RUNS TO COMPLETION THERE ARE 'NR' ROOTS TO BE
C  FOUND IN THE VECTOR 'ZR'(I),I=1,'NR'.
C
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (MSL=20, MSIG=10)
C
      LOGICAL ABRET,FAIL,LPRINT,ADJPER,PREX
      DOUBLE COMPLEX ZR,SSR,CEN
C
      DIMENSION ZR(*),SR(MSL),SSR(0:MSIG,MSL)
C
      COMMON /RSCALE/ SCALE,CEN
      COMMON /OUT/    LPRINT,IW
      COMMON /RADSEP/ RSEP
      COMMON /EXR/    IETYPE,BASE
      COMMON /RENTRY/ PREX
C
C  FOR A FULL DESCRIPTION OF THE ELEMENTS OF THESE COMMONS
C  SEE THE HEADER TO SUBROUTINE 'CROOT', THE MAIN DRIVER.
C  ALSO SEE 'INSIDE' CALLED FROM 'EXROOT' FOR A
C  DETAILED DESCRIPTION OF THE COMMON '/EXR/'.
C
C
C  /EXR/     'IETYPE'=1 IS SET FOR AN ANNULAR EXTRACTION.
C            'BASE' IS SET AT THE DEFAULT VALUE OF 0.
C
C  /RENTRY/  THE LOGICAL VARIABLE 'PREX' INDICATES THAT
C            ROOTS HAVE ALREADY BEEN LOCATED.  ITS USE IS
C            DISCUSSED USING THE FOLLOWING SCENARIO.
C            AT THE FIRST CALL OF 'RECUR' PERMISSION IS
C            GIVEN TO ADJUST BOTH THE INNER AND OUTER RADII.
C            HOWEVER, IF A SECOND OR SUBSEQUENT CALL OF
C            'RECUR' IS MADE (AS MAY RESULT FROM A NON-FATAL
C            PROBLEM E.G. CONVERGENCE) AND ZEROS HAVE BEEN
C            ADDED TO THE ARRAY 'ZR' (I.E. NR.NE.0) THE INNER
C            RADIUS CANNOT BE MOVED AS IS INDICATED BY 'PREX'
C            BEING SET .TRUE..  TO MOVE THE CONTOUR WOULD LEAD
C            TO AMBIGUITIES OR MISSED ROOTS.  FOR ALL OTHER
C            CASES 'PREX' IS SET .FALSE..
C
C
      IF (LPRINT) WRITE (IW,10) NSIG,SCALE*RMIN,SCALE*RMAX
   10 FORMAT(1X,'RECUR  - ENTRY - NSIG=',I3/
     +       3X,'RMIN=',1PE12.5,2X,'RMAX=',1PE12.5)
C
C     INITIALIZE THE STACK
      ISL=1
      SR(ISL)=RMAX
C     PERMISSION TO ADJUST OUTER RADIUS GIVEN
      PREX=.FALSE.
      ADJPER=.TRUE.
      CALL ESIGR(NSIG,ISL,SR,SSR,ADJPER,ABRET,FAIL)
      IF (ABRET.OR.FAIL) THEN
C       FAILURE TO CALCULATE INITIAL STACK ENTRY
        WRITE (IW,20) ISL
   20   FORMAT(1X,'RECUR  - FAILURE IN ESIGR(INITIAL) - ISL=',I3/
     =         3X,'ABORTING HERE')
        FAIL=.TRUE.
        RETURN
      END IF
C
      ISL=2
      IF (RMIN.LE.1.E-6) THEN
C       DEGENERATE CIRCLE - HENCE CLEAR THIS STACK ENTRY
        SR(ISL)=0.
        DO 30 I=0,NSIG
          SSR(I,ISL)=(0.,0.)
   30   CONTINUE
      ELSE
C       NON DEGENERATE CIRCLE - CALCULATE THE ENTRY
        SR(ISL)=RMIN
C       PERMISSION TO ADJUST THE INNER RADIUS IS GIVEN
C       ONLY IF NO ROOTS HAVE ALREADY BEEN LOACTED
        PREX=NR.NE.0
        CALL ESIGR(NSIG,ISL,SR,SSR,ADJPER,ABRET,FAIL)
        IF (ABRET.OR.FAIL) THEN
C         AGAIN A STACK INITIALIZATION FAILURE.
          WRITE (IW,20) ISL
          FAIL=.TRUE.
          RETURN
        END IF
      END IF
C
C     AFTER THE INITIALIZATION IS COMPLETE DENY PERMISSION
C     FOR ARBITRARY ADJUSTMENTS TO BE MADE TO THE SEARCH
C     RADII IN 'ESIGR'.  INSTEAD, RELY UPON RADIAL BISECTION
C
C     PERMISSION TO PERFORM RADIAL BISECTION IS ALWAYS GIVEN
      PREX=.FALSE.
C
      ADJPER=.FALSE.
C
C
C     MAIN RECURSION LOOP
C
C     REPEAT
  100 CONTINUE
        PSCALE=SCALE
        IF (LPRINT) CALL PRTSTK(ISL,SR,SSR,'RECUR','RADIAL',
     +                          'RADIUS',PSCALE)
        N1=NINT(REAL(SSR(0,ISL-1)))
        N2=NINT(REAL(SSR(0,ISL)))
C       'N1' AND 'N2' ARE THE NUMBER OF ROOTS WITHIN R(ISL-1)
C       AND R(ISL) RESPECTIVELY
C
        IF ((N1-N2).GT.NSIG) THEN
C         THERE ARE TOO MANY ROOTS WITHIN THE SEARCH REGION
C         BETWEEN R(ISL-1) AND R(ISL).  THUS, THE REGION WILL
C         BE BISECTED (AND THE STACK RAISED) PROVIDED THAT THE
C         RADIAL SEPARATION OF THE CIRCLES IS SUFFICIENTLY
C         GREAT.  OTHERWISE, THE REGION WILL BE SECTORED USING
C         THE ANGULAR RECURSION ROUTINE, 'RECURT'.
C
          IF ((SR(ISL-1)-SR(ISL)).GT.RSEP) THEN
C           BISECT AND RAISE THE STACK
            IF (ISL.GE.MSL) THEN
              WRITE (IW,105) ISL
  105         FORMAT(1X,'RECUR  - STACK IS FULL AT LENGTH',I3/
     +               3X,'INTEGRALS CONVERGING SLOWLY OR ',
     +                  'TOLERANCE TOO TIGHT'/3X,'ABORTING HERE')
              FAIL=.TRUE.
              RETURN
            ELSE
C             O.K. TO RAISE STACK. PUSH UP AND MAKE A HOLE.
              SR(ISL+1)=SR(ISL)
              DO 110 I=0,NSIG
                SSR(I,ISL+1)=SSR(I,ISL)
  110         CONTINUE
              SR(ISL)=0.5*(SR(ISL-1)+SR(ISL))
              IF (LPRINT) WRITE (IW,120) ISL,ISL+1
  120         FORMAT(1X,'RECUR  - RADIAL STACK TO BE RAISED ',
     +                  'FROM ',I2,' TO ',I2)
              CALL ESIGR(NSIG,ISL,SR,SSR,ADJPER,ABRET,FAIL)
              IF (FAIL) RETURN
              IF (ABRET) THEN
C               ABORTED RETURN FROM 'ESIGR'
                IF (LPRINT) WRITE (IW,130)
  130           FORMAT(1X,'RECUR  - TROUBLE IN ESIGR(BISECT)'/
     +                 3X,'RETURN TO CROOT')
                RMIN=SR(ISL+1)
                RMAX=SR(1)
                RETURN
              ELSE
C               NORMAL RETURN FROM 'ESIGR'. INCREMENT STACK
C               LENGTH AND GO AROUND FOR ANOTHER TRY AT ROOT
C               EXTRACTION.
C
                ISL=ISL+1
              END IF
C
            END IF
C
          ELSE
C           R(ISL-1) AND R(ISL) ARE WITHIN THE TOLERANCE REQUIRED
C           FOR A SECTOR EXTRACTION USING 'RECURT'.
C
            CALL RECURT(NSIG,ISL,SR,SSR,ABRET,FAIL,NR,ZR)
            IF (FAIL) RETURN
            IF (ABRET) THEN
C             UNSUCCESSFUL SECTORING OF THE ANNULUS BETWEEN
C             R(ISL) AND R(ISL-1).
              IF (LPRINT) WRITE (IW,140)
  140         FORMAT(1X,'RECUR  - TROUBLE IN RECURT'/
     +               3X,'RETURN TO CROOT')
              RMIN=SR(ISL)
              RMAX=SR(1)
              RETURN
            ELSE
C             NORMAL RETURN FROM RECURT - STACK LOWERED
              IF (LPRINT) WRITE (IW,150) ISL,ISL-1
  150         FORMAT(1X,'RECUR   - STACK LOWERED FROM ',I2,' TO ',I2)
              ISL=ISL-1
            END IF
C
          END IF
C
        ELSE
C         THERE ARE LESS THAN 'NSIG' ROOTS WITHIN THE ANNULUS
C         AND SO THE ROOTS MAY BE CALCULATED.
          IETYPE=1
          BASE=0.
C         THIS MEANS THAT ROOT EXTRACTION OCCURS WITHIN AN
C         ANNULAR REGION
          CALL EXROOT(ISL,SR,SSR,NR,ZR,ABRET)
          IF (ABRET) THEN
C           UNSUCCESSFUL ROOT EXTRACTION. GENERALLY THIS IS
C           CAUSED BY INTEGRATION TOLERANCES BEING TOO SLACK
C           THEREBY RESULTING IN POOR ESTIMATES FOR THE ZEROS
C           WHICH ARE SUBSEQUENTLY REFINED OUTSIDE THE SEARCH
C           REGION.
            IF (LPRINT) WRITE (IW,160)
  160       FORMAT(1X,'RECUR  - TROUBLE IN EXROOT'/
     +             3X,'RETURN TO CROOT')
            RMIN=SR(ISL)
            RMAX=SR(1)
            FAIL=.FALSE.
            RETURN
          ELSE
C           SUCCESSFUL RETURN FROM 'EXROOT'
C           CONSEQUENTLY LOWER THE STACK
            IF (LPRINT) WRITE (IW,170) ISL,ISL-1
  170       FORMAT(1X,'RECUR  - STACK LOWERED FROM ',I2,' TO ',I2)
            ISL=ISL-1
          END IF
C
        END IF
C
      IF (ISL.GT.1) GOTO 100
C     UNTIL (ISL.EQ.1)
C
C
      IF (LPRINT) WRITE (IW,200)
  200 FORMAT(1X,'RECUR  - NORMAL EXIT - BACK TO CROOT')
C
      FAIL=.FALSE.
      RETURN
      END
      SUBROUTINE PRTSTK(L,S,SS,CALLER,TYPE,HEADER,PSCALE)
C
C  'PRTSTK' PRINTS A SUMMARY OF THE PROGRAM STACKS.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (MSL=20, MSIG=10)
C
      CHARACTER*(*) CALLER,TYPE,HEADER
      LOGICAL LPRINT
      DOUBLE COMPLEX SS
C
      DIMENSION S(MSL),SS(0:MSIG,MSL)
C
      COMMON /OUT/    LPRINT,IW
C
C
      IF (LPRINT) THEN
        WRITE (IW,10)
   10   FORMAT(/1X,80('*'))
        WRITE (IW,20) CALLER,TYPE,L
   20   FORMAT(1X,A,'  - SUMMARY OF ',A,' STACK OF LENGTH',I3)
        WRITE (IW,30) HEADER
   30   FORMAT(1X,'LEVEL',T11,A6,T27,'NUMBER OF ROOTS')
        WRITE (IW,40) (I,PSCALE*S(I),SS(0,I),I=1,L)
   40   FORMAT(1X,I3,T8,1PE12.5,T22,1PE12.5,1X,1PE12.5)
        WRITE (IW,50)
   50   FORMAT(1X,80('*')/)
      END IF
C
      RETURN
      END
      SUBROUTINE ESIGR(NSIG,ISL,SR,SSR,ADJPER,ABRET,FAIL)
C
C    'ESIGR' GENERATES SUMS OF POWERS OF ROOTS WITHIN THE
C  CIRCLE OF RADIUS 'SR'('ISL').  FOR P=0,1...NSIG THE
C  FOLLOWING SUMS OF Z(I)**('IPOWER'*P) ARE GENERATED BY
C  INTEGRATING AROUND THE CIRCLE USING THE ROUTINE 'TRAP'
C  EMPLOYING THE TRAPEZOIDAL RULE.  THESE SUMS ARE PUT
C  ONTO THE STACK 'SSR' AT LEVEL 'ISL'.  AN UNSUCCESSFUL
C  RETURN IS INDICATED BY THE VARIABLE 'ABRET' BEING SET
C  .TRUE..  DURING INITIALIZATION OF THE STACK AT LEVELS
C  1 AND 2 PERMISSION TO MAKE ADJUSTMENTS TO THE SEARCH
C  RADII IS GIVEN ACCORDING TO THE LOGICAL VARIABLE 'ADJPER'.
C  'FAIL' SIGNIFIES AN IMMEDIATE ABORT OF THE PROGRAM.
C
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (MSL=20, MSIG=10)
C
      INTEGER TCROOT,TESIGR,TESIGT
      DOUBLE COMPLEX SSR,CEN,ARC
      LOGICAL ADJPER,ABRET,LPRINT,FAIL,PREX
C
      DIMENSION SSR(0:MSIG,MSL),SR(MSL),ADJ(2)
C
      EXTERNAL ARC
C
      COMMON /POWER/  IPOWER
      COMMON /ADJRAD/ ADJ
      COMMON /RSCALE/ SCALE,CEN
      COMMON /TOLI/   TOLINT,TINT
      COMMON /OUT/    LPRINT,IW
      COMMON /FCONST/ RAD,DUMMY
      COMMON /MDIFF/  TCROOT,TESIGR,TESIGT
      COMMON /RENTRY/ PREX
C
C  /FCONST/  THIS COMMON CONTAINS THE CONSTANTS FOR USE
C            IN THE INTEGRATION ROUTINE 'TRAP', VIA 'ARC'.
C            FOR EXAMPLE, IF THE CONTOUR IS THE ARC OF A
C            CIRCLE THEN THE CONSTANT IS THE RADIUS OF IT.
C            THIS COMMON IS ALSO ACCESSED IN THE ROUTINE
C            'ESIGT' CALLED FROM THE ANGULAR RECURSION
C            PROCEDURE 'RECURT' WHEREIN THE CONSTANT IS
C            EXP(I*THETA) WHERE THETA IS THE ANGLE OF
C            INCLINATION OF A LINE SEGMENT BOUNDING THE
C            SECTOR.
C
C  /RENTRY/  FOR A DESCRIPTION OF THIS COMMON SEE 'RECUR'.
C
      DATA DPI/6.28318530718/
C
C
C
C     SET THE MAXIMUM NUMBER OF TIMES TROUBLE CAN OCCUR
C     WITHIN 'ESIGR' BEFORE ABORTING WITH 'ABRET' SET
C     .TRUE..  BUT, BE MORE LENIENT WITH STACK INITIAL-
C     IZATION ENTRIES.
      IF (ADJPER) THEN
        MTROUB=2*TESIGR
      ELSE
        MTROUB=TESIGR
      END IF
C
      NTROUB=0
      IF (LPRINT) WRITE (IW,10) ISL
   10 FORMAT(1X,'ESIGR  - ENTRY AT LEVEL',I3)
C
C
C     REPEAT
   20 CONTINUE
        RAD=SR(ISL)
        IF (LPRINT) WRITE (IW,30) RAD*SCALE
   30   FORMAT(1X,'ESIGR  - CURRENT RADIUS=',1PE12.5)
        A=0.
        B=DPI
        CALL TRAP('ARC',ARC,A,B,NSIG,SSR(0,ISL),ABRET)
C
        IF (ABRET) THEN
C         TROUBLE HAS OCCURRED WITH THE INTEGRATION ROUTINE.
C         GENERALLY, THIS IS CAUSED BY THE CONTOUR PASSING
C         TOO CLOSE TO A ZERO.
          NTROUB=NTROUB+1
          IF (LPRINT) WRITE (IW,40) NTROUB,MTROUB
   40     FORMAT(1X,'ESIGR  - TROUBLE IN TRAP ',I2,'/',I2,' TIMES')
C         TAKE EVASIVE ACTION BY SHIFTING THE CONTOUR ONLY
C         IF ALLOWED.  PERMISSION IS ALWAYS GIVEN TO ADJUST
C         THE CONTOUR RADIUS UNLESS, DUE TO A SECOND OR
C         SUBSEQUENT CALL OF 'RECUR', THERE IS A NECESSITY
C         NOT TO SHIFT THE INITIAL INNER CONTOUR.
C
          IF (PREX) THEN
            WRITE (IW,45) SCALE*RAD
   45       FORMAT(1X,'ESIGR  - PERMISSION TO MOVE CONTOUR ',
     +                'OF RADIUS ',1PE12.5,' IS DENIED.'/
     +             3X,'OTHERWISE ROOTS MAY BE MISSED ',
     +                'OR DUPLICATED'/
     +             3X,'ABORTING HERE')
            FAIL=.TRUE.
            RETURN
          END IF
C
          IF (ADJPER) THEN
C           THE RADIUS IS SCALED ONLY FOR INITIALIZATION
C           OF THE STACK.
            RAD=ADJ(ISL)*SR(ISL)
            IF (LPRINT) WRITE (IW,50) SCALE*SR(ISL),SCALE*RAD
   50       FORMAT(1X,'ESIGR  - RADIUS ADJUSTED FROM ',1PE12.5
     +      ,' TO ',1PE12.5)
            SR(ISL)=RAD
          ELSE
C           MOVE THE CONTOUR SO THAT THE NEW RADIUS IS THE
C           AVERAGE OF THE CURRENT RADIUS AND THE NEXT STACKED
C           RADIUS JUST IN FROM 'RAD'
            RAD=0.5*(SR(ISL)+SR(ISL+1))
            IF (LPRINT) WRITE (IW,50) SR(ISL)*SCALE,RAD*SCALE
            SR(ISL)=RAD
          END IF
        END IF
      IF (ABRET. AND. (NTROUB.LT.MTROUB)) GOTO 20
C     UNTIL ((.NOT.ABRET) .OR. (NTROUB.GE.MTROUB))
C
C
      IF (.NOT.ABRET) THEN
C       A NORMAL EXIT FROM 'ESIGR'
C       JUST TO BE SURE THAT ALL IS WELL, CHECK THAT THE
C       NUMBER OF ROOTS FOUND IS SUFFICIENTLY CLOSE TO
C       AN INTEGER.
        RL=REAL(SSR(0,ISL))
        AG=AIMAG(SSR(0,ISL))
        IF ((ABS(RL-FLOAT(NINT(RL))).GT.TINT) .OR.
     +      (ABS(AG).GT.TINT)) THEN
C         THE INTEGRATION HAS FAILED TO CONVERGE ADEQUATELY.
C         SIGNAL THIS AND RETURN TO 'RECUR' AND 'CROOT' IN ORDER
C         TO TIGHTEN THE INTEGATION TOLERANCES.
          ABRET=.TRUE.
          IF (LPRINT) WRITE (IW,60) ISL,RL,AG
   60     FORMAT(1X,'ESIGR  - SIGMA(0',I3,')=',1P2E12.5,
     +           ' IS NOT AN INTEGER.')
        ELSE
C         ALL IS WELL
          NROOTS=NINT(RL)
          IF (LPRINT) WRITE (IW,70) NROOTS,SR(ISL)*SCALE
   70     FORMAT(1X,'ESIGR  - ',I3,' ROOTS WITHIN RADIUS=',
     +              1PE12.5)
        END IF
        FAIL=.FALSE.
      ELSE
C       TOO MUCH TROUBLE IN FINDING A SATISFACTORY CONTOUR
C       ISSUE DIAGNOSTIC AND GIVE UP HERE.
        WRITE (IW,75)
   75   FORMAT(1X,'ESIGR  - ',
     +         'TOO MUCH TROUBLE IN LOCATING A SATISFACTORY',
     +         ' CONTOUR'/3X,'ABORTING HERE')
        FAIL=.TRUE.
      END IF
C
      IF (LPRINT) WRITE (IW,80)
   80 FORMAT(1X,'ESIGR  - RETURN TO RECUR')
C
C
      RETURN
      END
      SUBROUTINE RECURT(NSIG,ISR,SR,SSR,ABRET,FAIL,NR,ZR)
C
C    'RECURT' IS THE RECURSION DRIVER FOR THE SECTOR ROOT
C  EXTRACTION.  THIS ROUTINE IS ENTERED IF THE TWO RADII,
C  'RA'='SR'('ISR') AND 'RB'='SR'('ISR'-1) BE WITHIN A TOLERANCE
C  'RSEP' (USED WITHIN 'RECUR').  IT OPERATES TWO STACKS
C  'SA' FOR SECTOR ANGLES AND 'SSA' FOR SUMS OF POWERS OF
C  ROOTS WHEN EXTRACTING ROOTS IN THE ANNULUS BETWEEN 'RA'
C  AND 'RB'.  AGAIN, 'NSIG' IS THE MAXIMUM NUMBER OF ROOTS
C  THAT MAY BE EXTRACTED AT ANY ONE TIME.  THE ROOTS
C  EXTRACTED ARE STORED IN 'ZR' AND 'NR' IS THE CUMULATIVE
C  NUMBER OF ROOTS EXTRACTED SO FAR.  SHOULD 'RECURT' FAIL
C  TO EXTRACT ALL THE ROOTS WITHIN THE ANNULUS, 'NR' IS NOT
C  UPDATED, 'ABRET' IS SET .TRUE. (SIGNIFYING AN ABNORMAL
C  RETURN) AND CONTROL RETURNS TO 'RECUR' AND THEN BACK TO
C  'CROOT' WHERE THE INTEGRATION TOLERANCES ARE TIGHTENED.
C
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (MSL=20, MSIG=10)
C
      LOGICAL ABRET,FAIL,LPRINT,INIT
      DOUBLE COMPLEX SSR,ZR,CEN,T,SSA
C
      DIMENSION SR(MSL),SSR(0:MSIG,MSL),ZR(*),SA(MSL)
      DIMENSION SSA(0:MSIG,MSL)
C
      COMMON /POWER/  IPOWER
      COMMON /RSCALE/ SCALE,CEN
      COMMON /OUT/    LPRINT,IW
      COMMON /EXR/    IETYPE,BASE
      COMMON /ESTRAD/ RA,RB
C
C  /EXR/     'IETYPE'=2 FOR A SECTOR EXTRACTION.  'BASE' REFERS
C            TO THE BASE ANGLE OF INTEGRATION AND IS USED FOR
C            ASSESSING WHETHER A ROOT IS INSIDE THE GIVEN SEARCH
C            REGION (AS IS DONE BY 'INSIDE').
C
C  /ESTRAD/  'RA' AND 'RB' ARE THE INNER AND OUTER RADII OF THE
C            SECTOR AROUND WHICH INTEGRALS ARE TO BE EVALUATED.
C            THIS IS USED IN 'ESIGT' AND 'INSIDE', WHICH
C            REQUIRES THE INFORMATION FOR DETERMINING WHETHER
C            THE EXTRACTED ROOTS LIE INSIDE THE SEARCH REGION.
C
C
      DATA PI/3.14159265359/,  DPI/6.28318530718/
C
C
      IF (LPRINT) WRITE (IW,10) NSIG,ISR,SCALE*SR(ISR),
     +                          ISR-1,SCALE*SR(ISR-1)
   10 FORMAT(1X,'RECURT - ENTRY - NSIG=',I3,' - SECTOR EXTRACTION'/
     +     2(1X,'R(',I2,') = ',1PE12.5,4X))
C
C     NOTE THE NUMBER OF ROOTS BETWEEN 'RA' AND 'RB' AND
C     INITIALIZE THE BASE AND TOP OF THE STACK.  ALSO, NOTE
C     HOW MANY ROOTS HAVE BEEN FOUND ALREADY IN CASE 'RECURT'
C     IS NOT SUCCESSFUL.
C
      RA=SR(ISR)
      RB=SR(ISR-1)
      IETYPE=2
      NZ=NR
      DO 20 I=0,NSIG
        SSA(I,1)=SSR(I,ISR-1)-SSR(I,ISR)
        SSA(I,2)=(0.,0.)
   20 CONTINUE
C
C     NOW START TO SCAN FOR A SATISFACTORY PLACE TO DO
C     A LINE INTEGRAL ALONG A RAY.
C
      ISL=2
      SA(ISL)=0.
      INIT=.TRUE.
      CALL ESIGT(NSIG,ISL,SA,SSA,INIT,ABRET,FAIL)
      IF (ABRET.OR.FAIL) THEN
C       CANNOT EVEN GET STARTED - ABORT
        WRITE (IW,30)
   30   FORMAT(1X,'RECURT - FAILURE IN ESIGT(INITIAL)'/
     +         3X,'ABORTING HERE')
        FAIL=.TRUE.
        RETURN
      ELSE
C       IN REASONABLE SHAPE - NOTE THE STARTING ANGLE.
        BASE=SA(ISL)
        IF (IPOWER.EQ.1) THEN
          SA(1)=SA(ISL)+DPI
        ELSE
          SA(1)=SA(ISL)+PI
        END IF
        INIT=.FALSE.
      END IF
C     INITIALIZATION COMPLETE
C
C     MAIN RECURSION LOOP
C
C     REPEAT (UNTIL STACK EMPTY)
  100 CONTINUE
        PSCALE=1.
        IF (LPRINT) CALL PRTSTK(ISL,SA,SSA,'RECURT','ANGULAR',
     +                          'ANGLE',PSCALE)
        N1=NINT(REAL(SSA(0,ISL-1)))
        N2=NINT(REAL(SSA(0,ISL)))
C       N1 AND N2 ARE THE NUMBER OF ROOTS BETWEEN THE TWO
C       RAYS (WITHIN THE ANNULUS) ON TOP OF THE STACK.
C
        IF ((N1-N2).GT.NSIG) THEN
C         TOO MANY ROOTS IN THE SEARCH REGION - BISECT
C         AND RAISE THE STACK IF THERE IS ROOM.
          IF (ISL.GE.MSL) THEN
C           STACK FULL - ABORT RUN
            WRITE (IW,105) ISL
  105       FORMAT(1X,'RECURT - STACK IS FULL A LENGTH',I3/
     +             3X,'INTEGRALS CONVERGING TOO SLOWLY OR ',
     +                'TOLERANCES ARE TOO TIGHT'/
     +             3X,'ABORTING HERE')
            FAIL=.TRUE.
            RETURN
          ELSE
C           O.K. TO RAISE STACK
            SA(ISL+1)=SA(ISL)
            DO 110 I=0,NSIG
              SSA(I,ISL+1)=SSA(I,ISL)
  110       CONTINUE
            SA(ISL)=0.5*(SA(ISL-1)+SA(ISL))
            IF (LPRINT) WRITE (IW,120) ISL,ISL+1
  120       FORMAT(1X,'RECURT - ANGULAR STACK TO BE RAISED ',
     +                'FROM LEVEL ',I2,' TO ',I2)
            CALL ESIGT(NSIG,ISL,SA,SSA,INIT,ABRET,FAIL)
            IF (FAIL) RETURN
            IF (ABRET) THEN
C             ABNORMAL RETURN FROM 'ESIGT'
              IF (LPRINT) WRITE (IW,130)
  130         FORMAT(1X,'RECURT - TROUBLE IN ESIGT(BISECT)'/
     +               3X,'RETURN TO RECUR')
              RETURN
            ELSE
C             NORMAL RETURN FROM 'ESIGT'. INCREMENT STACK AND
C             GO AROUND AGAIN.
              ISL=ISL+1
            END IF
          END IF
C
        ELSE
C         THERE ARE LESS THAN 'NSIG' ROOTS WITHIN THE SECTOR
C         AND SO THEY MAY BE EXTRACTED.
          CALL EXROOT(ISL,SA,SSA,NZ,ZR,ABRET)
          IF (ABRET) THEN
C           UNSUCCESSFUL ROOT EXTRACTION
            IF (LPRINT) WRITE (IW,160)
  160       FORMAT(1X,'RECURT - TROUBLE IN EXROOT'/
     +             3X,'RETURN TO RECUR')
            FAIL=.FALSE.
            RETURN
          ELSE
C           SUCCESSFUL ROOT EXTRACTION - LOWER STACK
            IF (LPRINT) WRITE (IW,170) ISL,ISL-1
  170       FORMAT(1X,'RECURT - STACK LOWERED FROM LEVEL ',I2,
     +                ' TO ',I2)
            ISL=ISL-1
          END IF
        END IF
C
      IF (ISL.GT.1) GOTO 100
C     UNTIL (ISL.EQ.1)
C
C
      IF (LPRINT) WRITE (IW,200)
  200 FORMAT(1X,'RECURT - NORMAL EXIT - RETURN TO RECUR')
C     UPDATE THE NUMBER OF ROOTS ONA SUCCESSFUL RETURN
      NR=NZ
      FAIL=.FALSE.
C
C
      RETURN
      END
      SUBROUTINE ESIGT(NSIG,ISL,SA,SSA,INIT,ABRET,FAIL)
C
C    'ESIGT' GENERATES SUMS OF POWERS OF ROOTS WITHIN THE
C  SECTOR BOUNDED BY THE RAYS THETA='SA'('ISL') AND THETA=
C  'SA'('ISL'-1) AND THE RADII 'RA' AND 'RB' CONTAINED IN
C  THE COMMON '/ESTRAD/'.  THE SUMS OF POWERS ARE KEPT ON
C  THE STACK 'SSA' AT LEVEL 'ISL'.  AN UNSUCCESSFUL RETURN
C  FROM 'ESIGT' IS INDICATED BY EITHER OF THE LOGICAL
C  VARIABLES 'ABRET' OR 'FAIL' BEING SET .TRUE..  'ABRET'
C  SIGNALS A NON-FATAL ERROR - E.G. POOR CONVERGENCE
C  WHICH CAN BE REMEDIED BY TIGHTENING THE INTEGRATION
C  TOLERANCES.  ON THE OTHER HAND, 'FAIL' INDICATES A
C  FATAL ERROR FROM WHICH RECOVERY IS IMPOSSIBLE AND LEADS
C  TO A PROGRAM ABORT.  'INIT' SIGNIFIES THE INITIAL ENTRY
C  DURING WHICH A SATISFACTORY STARTING RAY IS SOUGHT.
C
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (MSL=20, MSIG=10)
C
      INTEGER TCROOT,TESIGR,TESIGT
      LOGICAL ABRET,FAIL,INIT,LPRINT
      DOUBLE COMPLEX SSA,CEN,T,RAY,ARC
C
      EXTERNAL ARC,RAY
C
      DIMENSION T(0:MSIG),SSA(0:MSIG,MSL),SA(MSL)
C
      COMMON /POWER/  IPOWER
      COMMON /ADJANG/ ADJ
      COMMON /RSCALE/ SCALE,CEN
      COMMON /TOLI/   TOLINT,TINT
      COMMON /OUT/    LPRINT,IW
      COMMON /FCONST/ EITR,EITI
      COMMON /MDIFF/  TCROOT,TESIGR,TESIGT
      COMMON /ESTRAD/ RA,RB
C
C  /FCONST/  'EITR' AND 'EITI' ARE THE CONSTANTS REQUIRED FOR
C            INTEGRATION ALONG A RAY USING THE ROUTINE 'TRAP'
C            WITH THE FUNCTION 'RAY'.  SEE ALSO 'ESIGR',
C            'ARC' AND 'RAY' FOR A FULLER DESCRIPTION.
C
C  /ESTRAD/  'RA' AND 'RB' ARE THE INNER AND OUTER RADII OF THE
C            ANNULAR SECTOR.  SEE ALSO 'RECURT' AND 'INSIDE'.
C
C
      DATA PI/3.14159265359/,  DPI/6.28318530718/
C
C
      IF (LPRINT) WRITE (IW,10) ISL
   10 FORMAT(1X,'ESIGT  - ENTRY AT LEVEL ',I3)
      IF (LPRINT) WRITE (IW,15) SA(ISL)
   15 FORMAT(1X,'ESIGT  - CURRENT ANGLE=',1PE12.5)
C
      IF (INIT) THEN
C       INITIALIZATION OF THE SECTOR.  SEEK A
C       SATISFACTORY RAY TO COMMENCE THE SECTORING.
        IF (LPRINT) WRITE (IW,20)
   20   FORMAT(1X,'ESIGT  - CONTOUR INITIALIZATION')
        NTROUB=0
        MTROUB=4*TESIGT
        EITR=COS(SA(ISL))
        EITI=SIN(SA(ISL))
        CALL TRAP('RAY',RAY,RA,RB,NSIG,T,ABRET)
        IF (ABRET) NTROUB=NTROUB+1
C
C       WHILE (ABRET .AND. (NTROUB.LT.MTROUB)
   30   IF (.NOT.ABRET .OR. (NTROUB.GE.MTROUB)) GOTO 40
          IF (LPRINT) WRITE (IW,35) NTROUB,MTROUB,SA(ISL)
   35     FORMAT(1X,'ESIGT  - TROUBLE IN TRAP ',I2,'/',I2,
     +              'TIMES'/
     +           1X,'SEARCH ANGLE CHANGED TO ',1PE12.5)
          SA(ISL)=SA(ISL)-ADJ
          EITR=COS(SA(ISL))
          EITI=SIN(SA(ISL))
          CALL TRAP('RAY',RAY,RA,RB,NSIG,T,ABRET)
        GOTO 30
C       END WHILE
C
   40   CONTINUE
        IF (ABRET) THEN
C         FAILED IN INITIALIZATION
          WRITE (IW,50)
   50     FORMAT(1X,'ESIGT  - TOO MUCH TROUBLE IN LOCATING ',
     +              'A SATISFACTORY INITIAL RAY'/
     +           3X,'ABORTING HERE')
          FAIL=.TRUE.
          RETURN
C
        ELSE
C         INITIALIZATION COMPLETED
          IF (LPRINT) WRITE (IW,60) SA(ISL)
   60     FORMAT(1X,'ESIGT  - INITIALIZATION COMPLETE - ',
     +              'SEARCH ANGLE=',1PE12.5)
        END IF
C
      ELSE
C       NORMAL INTEGRATION AROUND A SECTOR CONTOUR
        MTROUB=TESIGT
        NTROUB=0
        EITR=COS(SA(ISL+1))
        EITI=SIN(SA(ISL+1))
        CALL TRAP('RAY',RAY,RA,RB,NSIG,SSA(0,ISL),ABRET)
C       NO NEED TO TEST 'ABRET' AS THIS INTEGRATION MUST
C       HAVE BEEN PERFORMED PREVIOUSLY.
C
C       NOW FOR THE NEW RAY
        EITR=COS(SA(ISL))
        EITI=SIN(SA(ISL))
        CALL TRAP('RAY',RAY,RA,RB,NSIG,T,ABRET)
        IF (ABRET) NTROUB=NTROUB+1
C
C       WHILE (ABRET .AND. (NTROUB.LT.MTROUB))
   70   IF (.NOT.ABRET .OR. (NTROUB.GE.MTROUB)) GOTO 100
          SA(ISL)=0.5*(SA(ISL)+SA(ISL+1))
          IF (LPRINT) WRITE (IW,35) NTROUB,MTROUB,SA(ISL)
          EITR=COS(SA(ISL))
          EITI=SIN(SA(ISL))
          CALL TRAP('RAY',RAY,RA,RB,NSIG,T,ABRET)
          IF (ABRET) NTROUB=NTROUB+1
        GOTO 70
C       END WHILE
C
  100   IF (ABRET) THEN
C         FAILED IN BISECTION
          WRITE (IW,110)
  110     FORMAT(1X,'ESIGT  - TOO MUCH TROUBLE IN LOCATING ',
     +              'A SATISFACTORY RADIAL PATH'/
     +           3X,'ABORTING HERE')
          FAIL=.TRUE.
          RETURN
        ELSE
C         RADIAL INTEGRATIONS COMPLETED
          DO 120 I=0,NSIG
            SSA(I,ISL)=SSA(I,ISL)-T(I)
  120     CONTINUE
        END IF
C
C       NOW FOR THE CIRCULAR ARCS.
        TA=SA(ISL+1)
        TB=SA(ISL)
        EITR=RB
        CALL TRAP('ARC',ARC,TA,TB,NSIG,T,ABRET)
        IF (ABRET) THEN
C         REAL TROUBLE ON A CIRCULAR ARC SINCE THIS SHOULD
C        HAVE BEEN COMPLETED ALREADY.
          WRITE (IW,130)
  130     FORMAT(1X,'ESIGT  - REAL STRIFE ON A CIRCULAR ARC'/
     +           3X,'ABORTING HERE')
          FAIL=.TRUE.
          RETURN
        ELSE
C         ACCUMULATE SIGMA VALUES
          DO 140 I=0,NSIG
            SSA(I,ISL)=SSA(I,ISL)+T(I)
  140     CONTINUE
        END IF
C
C       AND NOW THE OTHER CIRCULAR ARC
        IF (RA.GT.1.E-6) THEN
        EITR=RA
        CALL TRAP('ARC',ARC,TA,TB,NSIG,T,ABRET)
        IF (ABRET) THEN
          WRITE (IW,130)
          FAIL=.TRUE.
          RETURN
        ELSE
          DO 150 I=0,NSIG
            SSA(I,ISL)=SSA(I,ISL)-T(I)
  150     CONTINUE
        END IF
        END IF
C
C       IF THE FUNCTION IS EVEN DOUBLE THE VALUES OF
C       'SSA'(I,'ISL').
        IF (IPOWER.EQ.2) THEN
          DO 155 I=0,NSIG
            SSA(I,ISL)=2.*SSA(I,ISL)
  155     CONTINUE
        END IF
        DO 156 I=0,NSIG
          SSA(I,ISL)=SSA(I,ISL+1)+SSA(I,ISL)
  156   CONTINUE
        IF (LPRINT) WRITE (IW,157) NSIG,(SSA(I,ISL),I=0,NSIG)
  157   FORMAT(1X,'ESIGT  - SIGMA(I),I=0, ',I2,' ARE:'/
     +        (3(2X,1P2E12.5))/(26X,2(2X,1P2E12.5)))
C
C
C       NOW CHECK THAT THE NUMBER OF ROOTS FOUND IS
C       SUFFICIENTLY CLOSE TO AN INTEGER.
        FAIL=.FALSE.
        RL=REAL(SSA(0,ISL))
        AG=AIMAG(SSA(0,ISL))
        IF ((ABS(RL-FLOAT(NINT(RL))).GT.TINT) .OR.
     +      (ABS(AG).GT.TINT)) THEN
C         FAILURE TO CONVERGE ADEQUATELY
          ABRET=.TRUE.
          IF (LPRINT) WRITE (IW,160) ISL,RL,AG
  160     FORMAT(1X,'ESIGT  - SIGMA(0,',I3,') = ',1P2E12.5,
     +              ' IS NOT AN INTEGER')
        ELSE
C         ALL IS WELL
          NROOTS=NINT(RL)
          IF (LPRINT) WRITE (IW,170) NROOTS
  170     FORMAT(1X,'ESIGT  - ',I3,' ROOTS LOCATED')
        END IF
C
      END IF
C
      IF (LPRINT) WRITE (IW,180)
  180 FORMAT(1X,'ESIGT  - RETURN TO  RECURT')
C
      RETURN
      END
      SUBROUTINE TRAP(TYPE,F,A,B,NSIG,S,ABRET)
C
C    THIS SUBROUTINE CALCULATES INTEGRALS (USING THE
C  TRAPEZOIDAL RULE) OF THE FUNCTIONS (Z**P)*'F' FROM X='A'
C  TO X='B' AND FOR P=0,1,...,NSIG.  HERE, X IS THE
C  INDEPENDENT PARAMETER WHICH IN THE CASE OF INTEGRALS
C  AROUND AN ARC OF A CIRCLE IS THE ANGLE, AND IN THE CASE
C  OF AN INTEGRAL ALONG A RADIAL LINE IS THE RADIAL DISTANCE.
C  THE RESPECTIVE CONSTANTS, THE RADIUS AND THE ANGLE(OR
C  SOME DERIVED FUNCTION OF IT) ARE COMMUNICATED TO THE
C  ACTUAL FUNCTIONS 'ARC' AND 'RAY' VIA THE COMMON /FCONST/.
C  RESULTS ARE PASSED THROUGH THE COMPLEX VECTOR 'S'.  'ABRET'
C  IS A LOGICAL VARIABLE WHICH SIGNALS AN ABORTED RETURN. THIS
C  IS GENERALLY CAUSED BY POOR CONVERGENCE OF INTEGRALS.
C
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (MBIS=20,MSIG=10)
C
      LOGICAL ABRET,LPRINT,CONVRG
      DOUBLE COMPLEX F,S,FZ,ZP,Z,T
      CHARACTER TYPE*(*)
      INTEGER TWON
C
      DIMENSION S(0:*),T(0:MSIG,0:MBIS)
C     WITH 'MBIS'=20, A MAXIMUM OF 2**MBIS (APPROX. 1000000)
C     POINTS ARE PLACED ON THE INTEGRATION CONTOUR.
C
      COMMON /POWER/  IPOWER
      COMMON /METHOD/ CRIT,MAXBIS
      COMMON /TOLI/   TOLINT,TINT
      COMMON /OUT/    LPRINT,IW
C
C
      IF (LPRINT) WRITE (IW,10) TYPE,NSIG
   10 FORMAT(1X,'TRAP   - ENTRY FOR ',A,' INTEGRAL WITH NSIG='
     +         ,I2)
C
      N=0
      TWON=1
      H=B-A
      DH=H
      IF (IPOWER.EQ.2) THEN
C       FOR FUNCTIONS HAVING EVEN SYMMETRY, WE WANT ONLY
C       THOSE ROOTS HAVING A POSITIVE REAL PART. HENCE,
C       WE HALVE THE INTEGRAL WEIGHT.
        DH=0.5*DH
      END IF
C
C     INITIALIZE THE INTEGRAL - ONE PANEL AND TWO POINTS
      DO 15 J=0,NSIG
        T(J,N)=(0.,0.)
   15 CONTINUE
      X=A
      DO 40 I=1,2
        FZ=F(X,Z)
        IF (ABS(FZ).GT.CRIT) THEN
C         TOO CLOSE TO A ZERO TO GET ADEQUATE CONVERGENCE
          IF (LPRINT) WRITE (IW,20) CRIT,FZ
   20     FORMAT(1X,'TRAP   - CRIT=',1PE12.5,' EXCEEDED. F(Z)=',
     +              1P2E12.5)
          ABRET=.TRUE.
          RETURN
        END IF
        IF (IPOWER.EQ.1) THEN
          ZP=Z
        ELSE
          ZP=Z*Z
        END IF
        DO 30 J=0,NSIG
          T(J,N)=T(J,N)+DH*FZ/2.
          FZ=FZ*ZP
   30   CONTINUE
        X=X+H
   40 CONTINUE
C
C     REPEAT (INTEGRATION UNTIL CONVERGED OR TAKEN TOO LONG)
  100 CONTINUE
C       IF (LPRINT) WRITE (IW,110) N,NSIG,(T(J,N),J=0,NSIG)
  110   FORMAT(1X,'TRAP   - INTEGRALS AT STEP ',I2,'.  ',
     +            'SIGMA(I),I=0,',I2,' ARE:'/
     +        3(2X,1P2E12.5)/(26X,2(2X,1P2E12.5)))
C
        N=N+1
        IF (N.GT.MAXBIS) THEN
          IF (LPRINT) WRITE (IW,120) MAXBIS
  120     FORMAT(1X,'TRAP   - MAX. NO. OF POINTS = 2**',I2,
     +              ' EXCEEDED - RETURN')
          ABRET=.TRUE.
          RETURN
        END IF
        NEWPAN=TWON
        TWON=2*TWON
        PREVH=H
        H=H/2.
        DH=DH/2.
C
C       HALVE THE PREVIOUS ESTIMATE AND THEN ADD ON THE
C       CONTRIBUTIONS FROM THE NEW POINTS.
        DO 130 J=0,NSIG
          T(J,N)=0.5*T(J,N-1)
  130   CONTINUE
C
        X=A+H
        DO 150 I=1,NEWPAN
          FZ=F(X,Z)
          IF (ABS(FZ).GT.CRIT) THEN
C           AGAIN TOO CLOSE TO A ZERO.
            IF (LPRINT) WRITE (IW,20) CRIT,FZ
            ABRET=.TRUE.
            RETURN
          END IF
C
          IF (IPOWER.EQ.1) THEN
            ZP=Z
          ELSE
            ZP=Z*Z
          END IF
C
          DO 140 J=0,NSIG
            T(J,N)=T(J,N)+DH*FZ
            FZ=FZ*ZP
  140     CONTINUE
C
          X=X+PREVH
  150   CONTINUE
C
C       TEST FOR CONVERGENCE
        IF (N.LT.4) THEN
C         TOO FEW ITERATIONS TO GET A SENSIBLE RESULT
          CONVRG=.FALSE.
        ELSE
C         NOW CHECK FOR CONVERGENCE
          DO 200 J=0,NSIG
            DEL=ABS(T(J,N)-T(J,N-1))
            TMAX=MAX(ABS(T(J,N)),ABS(T(J,N-1)))
            IF ((DEL.GT.TOLINT*TMAX) .AND. (DEL.GT.TOLINT))
     +      THEN
              CONVRG=.FALSE.
              GOTO 210
            ELSE
              CONVRG=.TRUE.
            END IF
  200     CONTINUE
C
  210     CONTINUE
        END IF
C
      IF (.NOT.CONVRG) GOTO 100
C     UNTIL (CONVRG)
C
C
C     SATISFACTORY CONVERGENCE
      DO 250 J=0,NSIG
        S(J)=T(J,N)
  250 CONTINUE
C
      IF (LPRINT) WRITE (IW,110) N,NSIG,(S(J),J=0,NSIG)
      IF (LPRINT) WRITE (IW,260)
  260 FORMAT(1X,'TRAP   - SATISFACTORILY COMPLETED')
      ABRET=.FALSE.
C
C
      RETURN
      END
      DOUBLE COMPLEX FUNCTION ARC(T,Z)
C
C    IN EVALUATING F'Z)/F(Z)/(2.*PI*I) AROUND A CIRCULAR
C  CONTOUR OF RADIUS 'R' (AS GIVEN IN THE COMMON '/FCONST/')
C  ,'ARC', WHICH IS A FUNCTION OF THE INDEPENDENT VARIABLE
C  'T' (THE POLAR ANGLE), REQUIRES EVALUATION.  'Z' IS THE
C  POINT AT WHICH THE FUNCTION IS EVALUATED.
C
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)

      DOUBLE COMPLEX Z,FZ,DZ,I,ZP,CEN
C
      COMMON /RSCALE/ SCALE,CEN
      COMMON /FCONST/ R,DUMMY
C
      DATA I/(0.D0,1.D0)/,  ONTPI/0.159154943092D0/

      Z=R*EXP(I*T)
      ZP=CEN+SCALE*Z
      CALL FNDER(ZP,FZ,DZ)
C
C     SCALE THE DERIVATIVE BECAUSE THE PROGRAM IS WORKING
C     WITH THE LINEARLY TRANSFORMED VARIABLE 'Z' RATHER
C     THAN THE USER'S PHYSICAL VARIABLE 'ZP'.
C
      DZ=SCALE*DZ
C
      IF (ABS(FZ).LE.1.E-12) THEN
C       JUST ABOUT STEPPED ON A ROOT.  HENCE INTEGRALS WILL
C       BE UNSTABLE. INFORM 'TRAP' SO THAT THE CALLING ROUTINE
C       CAN ADJUST THE INTEGRATION CONTOUR.
        ARC=(1.E10,1.E10)
      ELSE
C       NOT TOO CLOSE TO A ROOT
        ARC=Z*DZ*ONTPI/FZ
      END IF
C
C
      RETURN
      END
      DOUBLE COMPLEX FUNCTION RAY(R,Z)
C
C    THIS FUNCTION PERFORMS A SIMILAR TASK TO THAT OF
C  'ARC'.  IT OCCURS IN THE EVALUATION OF F'(Z)/F(Z)/
C  (2.*PI*I) ALONG A STRAIGHT LINE OF ANGLE 'T'.  TO SAVE
C  ON COMPUTATION TIME THE VARIABLE IN THE COMMON '/FCONST/'
C  IS EXP(I*'T').
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE COMPLEX Z,FZ,DZ,I,ZP,CEN,EIT
C
      COMMON /RSCALE/ SCALE,CEN
      COMMON /FCONST/ EITR,EITI
C
      DATA I/(0.,1.)/,  ONTPI/0.159154943092/
C
C
      EIT=CMPLX(EITR,EITI)
      Z=R*EIT
      ZP=CEN+SCALE*Z
      CALL FNDER(ZP,FZ,DZ)
      DZ=SCALE*DZ
C
      IF (ABS(FZ).LE.1.E-12) THEN
C       STEPPED ON A ROOT
        RAY=(1.E10,1.E10)
      ELSE
C       OTHERWISE
        RAY=-I*EIT*DZ*ONTPI/FZ
      END IF
C
C
      RETURN
      END
      SUBROUTINE EXROOT(ISL,SR,SS,NR,ZR,ABRET)
C
C    THIS SUBROUTINE PERFORMS THE EXTRACTION OF ROOTS WITHIN
C  A GIVEN REGION.  THE REGION SPECIFIED DEPENDS ON WHICH
C  ROUTINE CALLED 'EXROOT'.  IF THE ROUTINE WAS 'RECUR' AS
C  SPECIFIED BY 'ITYPE'=1 IN THE COMMON '/EXR/' THEN THE
C  REGION IS AN ANNULUS BOUNDED BY R='SR'('ISL') AND
C  R='SR'('ISL'-1).  ALTERNATIVELY, SHOULD 'EXROOT' HAVE
C  BEEN CALLED FROM 'RECURT' (THE ROUTINE FOR SECTORING
C  AN ANNULUS), AS SPECIFIED BY 'ITYPE'=2, THEN THE REGION
C  IS A SECTOR WHOSE BOUNDING RAYS HAVE ANGLES THETA=
C  'SR'('ISL') AND THETA='SR'('ISL'-1) AND OF INNER AND
C  OUTER RADII R='RA' AND R='RB'.  THE PARAMETERS 'RA' AND
C  'RB' ARE ALSO COMMUNICATED BY THE COMMON '/EXR/'.
C
C    THE ROUTINE USES THE SUMS OF POWERS OF ROOTS WITHIN
C  THE REGION AND APPLIES NEWTON'S IDENTITIES AS DISCUSSED
C  IN:
C    RALSTON, A. AND RABINOWITZ, P., 1978,
C    'A FIRST COURSE IN NUMERICAL ANALYSIS' (2ND EDITION)
C    ((TOKYO : MCGRAW-HILL KOGAKUSHA).
C  TO DERIVE AN EQUIVALENT POLYNOMIAL HAVING THE SAME ROOTS
C  AS THE FUNCTION WITHIN THE GIVEN SEARCH REGION.  THE
C  ROOTS OF THIS POLYNOMIAL ARE THEN CALCULATED USING
C  MULLER'S METHOD (REFERENCE TO THIS IS GIVEN IN THE
C  SUBROUTINE MULLER) AND ARE USED AS ESTIMATES OF THE ROOTS
C  OF THE ACTUAL FUNCTION.  THESE ARE SUBSEQUENTLY REFINED
C  USING MULLERS METHOD APPLIED TO THE ACTUAL FUNCTION.
C  ** AN ALTERNATIVE METHOD OF REFINEMENT SUCH AS THE
C  NEWTON-RAPHSON ITERATION (SINCE DERIVATIVES OF THE FUNCTION
C  ARE AVAILABLE) MAY EASILY BE INCORPORATED INTO THE
C  PROGRAMME. **
C
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (MSL=20,  MSIG=10,  MAXIT=200)
C     'MAXIT' IS THE MAXIMUM NUMBER OF ITERATIONS PERMITTED
C     BY 'MULLER' IN THE PROCESS OF EXTRACTING ROOTS.
C
      LOGICAL ABRET,LPRINT,IN,IN1,CEX
      DOUBLE COMPLEX ZR,SS,C,Z,FZ,DZ,FROOTS,CEN
C
      DIMENSION ZR(*),SR(MSL),SS(0:MSIG,MSL)
      DIMENSION CEX(MSIG),C(0:MSIG),FROOTS(MSIG)
C
      EXTERNAL POLY,RF
C
      COMMON /POWER/  IPOWER
      COMMON /TOLE/   EP1,EP2
      COMMON /EXPOLY/ N,C
      COMMON /OUT/    LPRINT,IW
      COMMON /RSCALE/ SCALE,CEN
C
C  /EXPOLY/  THIS COMMON CONTAINS THE DEGREE 'N' OF THE
C            EQUIVALENT POLYNOMIAL AND ITS COEFFICIENTS
C            C(0),C(1),..,C(N), WHERE C(I) IS THE COEFFICIENT
C            OF THE TERM Z**I.
C
C
C
      IF (LPRINT) WRITE (IW,10) ISL
   10 FORMAT(1X,'EXROOT - ENTRY - ISL=',I3)
      N1=NINT(REAL(SS(0,ISL-1)))
      N2=NINT(REAL(SS(0,ISL)))
      N=N1-N2
      IF (LPRINT) WRITE (IW,20) N,ISL-1,ISL
   20 FORMAT(1X,'EXROOT - ',I2,' NEW ROOTS BETWEEN LEVELS ',
     +       I3,' AND ',I3)
C
C
      IF (N.NE.0) THEN
C       A NON TRIVIAL NUMBER OF ROOTS TO EXTRACT.  GENERATE
C       THE COEFFICIENTS OF THE EQUIVALENT POLYNOMIAL BY
C       APPLYING NEWTON'S IDENTITIES.
        C(N)=(1.,0.)
        DO 40 M=1,N
          L=N-M
          C(L)=(0.,0.)
          DO 30 K=1,M
            C(L)=C(L)-(SS(K,ISL-1)-SS(K,ISL))*C(L+K)
   30     CONTINUE
          C(L)=C(L)/FLOAT(M)
   40   CONTINUE
C
C       IF (LPRINT) WRITE (IW,50) (M,C(M),M=N,0,-1)
   50   FORMAT(1X,'EXROOT - COEFFS. OF EQUIV. POLYNOMIAL'/
     +        (1X,'COEFF(',I2,') = ',1P2E12.5))
C
C       EQUIVALENT POLYNOMIALS HAVE NOW BEEN FORMED.
C       N.B. FOR EVEN FUNCTIONS ('IPOWER'=2) THIS POLY.
C       CONTAINS EVEN ORDER TERMS.  HENCE, THE ROOT
C       CALCULATED BY MULLER, PRESUMING THAT THE POLY.
C       IS OF DEGREE 'N' RATHER THAN 2*'N', WILL BE
C       THE SQUARE OF THE ACTUAL ROOT.
C
        HINIT=0.5
        NPREV=0
        ITMAX=MAXIT
C       CHOOSE SOME NUMBERS RELATED TO 'E' AND 'PI',
C       I.E. TRANSCENDENTAL, TO DERIVE THE INITIAL
C       GUESSES.  THIS AVOIDS PROBLEMS WITH POLYS.
C       HAVING ROOTS AT PRECISELY MULTIPLES OF
C       'HINIT'.
        DO 60 I=1,N
          FROOTS(I)=(0.115572735,0.086525598)
   60   CONTINUE
C
        CALL MULLER(POLY,HINIT,FROOTS,N,NPREV,ITMAX,EP1,EP2,CEX)
C
C       NOW CHECK THAT ALL ROOTS ARE INSIDE THE SEARCH REGION
        IN=.TRUE.
        IF (LPRINT) WRITE (IW,70)
   70   FORMAT(1X,'EXROOT - ROOT ESTIMATES FROM MULLER')
        IF (LPRINT) WRITE (IW,75)
   75   FORMAT(1X,'ZERO',7X,'ZERO ESTIMATE',15X,
     +            'POLYNOMIAL')
C
        DO 100 I=1,N
          Z=FROOTS(I)
          CALL POLY(Z,FZ)
          IF (IPOWER.EQ.2) FROOTS(I)=SQRT(FROOTS(I))
          Z=CEN+SCALE*FROOTS(I)
          IF (LPRINT) WRITE (IW,85) I,Z,FZ
   85     FORMAT(2X,I2,3X,1P2E12.5,2X,1P2E12.5)
          CALL INSIDE(FROOTS(I),SR(ISL),SR(ISL-1),
     +                RAD,ANG,IN1)
          IN=IN .AND. IN1
          IF (.NOT.IN1 .AND. LPRINT)
     +      WRITE (IW,90) SCALE*RAD,ANG
   90       FORMAT(1X,'EXROOT - **THIS ROOT OUTSIDE THE ',
     +                'SEARCH REGION**'/
     +             1X,'RADIUS=',1PE12.5,2X,'ARGUMENT=',1PE12.5)
  100   CONTINUE
        IF (.NOT.IN .AND. LPRINT) WRITE (IW,102)
  102   FORMAT(1X,'EXROOT - **TROUBLE IN ROOT ESTIMATION**')
C
C       NOW ATTEMPT TO IMPROVE THE ROOTS BY A SECOND USE
C       OF MULLER, THIS TIME WITH THE ACTUAL FUNCTION.
C
        HINIT=1.E-4
        CALL MULLER(RF,HINIT,FROOTS,N,NPREV,ITMAX,EP1,EP2,CEX)
        IN=.TRUE.
        IF (LPRINT) WRITE (IW,103)
  103   FORMAT(1X,'EXROOT - REFINED ROOTS')
        IF (LPRINT) WRITE (IW,104)
  104   FORMAT(1X,'ZERO',8X,'REFINED ZERO',16X,'FUNCTION',
     +        17X,'DERIVATIVE')
C
        DO 120 I=1,N
          Z=FROOTS(I)
          Z=CEN+SCALE*Z
          CALL FNDER(Z,FZ,DZ)
          IF (LPRINT) WRITE (IW,105) I,Z,FZ,DZ
  105     FORMAT(2X,I2,3X,1P2E12.5,2X,1P2E12.5,2X,1P2E12.5)
          CALL INSIDE(FROOTS(I),SR(ISL),SR(ISL-1),RAD,ANG,IN1)
          IF (.NOT.IN1 .AND. LPRINT)
     +       WRITE (IW,90) SCALE*RAD,ANG
          IN=IN .AND. IN1
          IF (CEX(I)) WRITE (IW,118) NR+I
  118     FORMAT(1X,'EXROOT - ITERATION COUNT IN MULLER EXCEEDED'/
     +           3X,'ROOT',I3,' MAY NOT BE ACCURATELY DETERMINED')
  120   CONTINUE
C
        IF (.NOT.IN) THEN
C         TROUBLE - TIGHTEN INTEGRATION TOLERANCES
          IF (LPRINT) WRITE (IW,150)
  150     FORMAT(1X,'EXROOT - ABNORMAL RETURN DUE TO ',
     +              'TROUBLE IN REFINEMENT')
          ABRET=.TRUE.
          RETURN
        ELSE
C         EVERYTHING O.K. NOTE THE ROOTS IN THE OUTPUT
C         ARRAY 'ZR'.
          DO 160 I=1,N
            ZR(NR+I)=CEN+SCALE*FROOTS(I)
  160     CONTINUE
          NR=NR+N
          ABRET=.FALSE.
        END IF
C
      ELSE
C       TRIVIAL CASE NO ROOTS TO EXTRACT
        ABRET=.FALSE.
      END IF
C
      IF (LPRINT) WRITE (IW,170) NR
  170 FORMAT(1X,'EXROOT - NORMAL RETURN WITH ',I3,' ROOTS')
C
C
      RETURN
      END
      SUBROUTINE INSIDE(Z,A,B,R,T,IN)
C
C    THIS ROUTINE TESTS TO SEE WHETHER A ROOT 'Z' HAS
C  BEEN LOCATED WITHIN THE GIVEN SEARCH REGION.  THE TWO
C  MODES OF USAGE ARE SPECIFIED BY THE PARAMETER 'ITYPE'
C  CONTAINED WITHIN THE COMMON '/EXR/'.
C
C  'ITYPE'=1 - THIS FORM OF USAGE IS CONTROLLED BY 'EXROOT'
C              CALLED FROM 'RECUR'.  'IN' IS TRUE IF THE
C              ROOT LIES WITHIN THE ANNULUS:
C              'A' .LE. ABS('Z') .LE. 'B'.
C
C  'ITYPE'=2 - THIS USAGE WOULD ARISE FROM A CALL TO 'EXROOT'
C              BY 'RECURT'.  HERE 'IN' IS TRUE IF THE ROOT
C              LIES IN THE SECTOR:
C              'C' .LE. ABS('Z') .LE. 'D',
C              'A' .LE. ARG('Z') .LE. 'B'.
C
C  THE PARAMETERS 'R' AND 'T' ARE THE MODULUS AND THE
C  ARGUMENT OF THE COMPLEX NUMBER 'Z'.
C
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE COMPLEX Z
      LOGICAL IN
C
      COMMON /EXR/    ITYPE,BASE
      COMMON /ESTRAD/ C,D
C
      DATA PI/3.14159265359/,  DPI/6.28318530718/
C
C
      R=ABS(Z)
      T=ATAN2(AIMAG(Z),REAL(Z))
C     FORCE T TO LIE IN THE INTERVAL (BASE,2*PI+BASE)
      T=T-DPI*IGIF(T/DPI)
      T=T-DPI*IGIF((T-BASE)/DPI)
C
      IF (ITYPE.EQ.1) THEN
C       ANNULUS
        RA=MIN(A,B)
        RB=MAX(A,B)
        IN=(R.GE.RA) .AND. (R.LE.RB)
C
      ELSE
C       SECTOR
        RA=MIN(C,D)
        RB=MAX(C,D)
        IN=(R.GE.RA) .AND. (R.LE.RB)
C
        TA=MIN(A,B)
        TB=MAX(A,B)
        IN=IN .AND. ((T.GE.TA) .AND. (T.LE.TB))
      END IF
C
      RETURN
      END
      INTEGER FUNCTION IGIF(X)
C
C    'IGIF' CALCULATES THE GREATEST INTEGER JUST LESS
C  THAN OR EQUAL TO THE REAL NUMBER 'X'.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      IGIF=INT(X)
      IF (X.LT.FLOAT(IGIF)) IGIF=IGIF-1
C
      RETURN
      END
      SUBROUTINE MULLER(F,HINIT,ZERO,N,NPREV,MAXIT,EP1,EP2,CEX)
C
C    'MULLER' DETERMINES UP TO 'N' ZEROS OF THE FUNCTION 'F'
C  USING MULLER'S METHOD INVOLVING QUADRATIC INTERPOLATION.
C  THIS VERSION OF THE ROUTINE HAS BEEN DERIVED FROM THE
C  REFERENCE BELOW, WITH SOME MINOR MODIFICATIONS.
C
C  CONTE, S. AND DE BOOR, C., 'ELEMENTARY NUMERICAL ANALYSIS -
C  AN ALGORITHMIC APPROACH', 3RD EDITION, 1980, (NEW YORK :
C  MCGRAW-HILL)
C
C  'HINIT' IS THE INITIAL VALUE OF THE STEP H USED IN CASTING
C  AROUND LOOKING FOR ROOTS.  'ZERO'('NPREV'+1),..,'ZERO'('N')
C  CONTAIN INITIAL GUESSES OF THE POSITIONS OF THE ZEROS TO BE
C  FOUND. IF NOTHING IS KNOWN THEN 0 IS AS GOOD A GUESS AS ANY
C  'MAXIT' IS THE MAXIMUM NUMBER OF FUNCTION EVALUATIONS PER
C  ZERO.THE ITERATION IS STOPPED IF ABS('H').LT.'EP1'*ABS('Z')
C  WHERE 'H' IS THE LATEST CHANGE IN THE ESTIMATE OF THE ZERO
C  AND 'Z' IS THE ZERO.  ALTHOUGH THIS CRITERION MAY NOT BE
C  MET, ITERATION IS STOPPED IF ABS('F'('Z')) .LT. 'EP2'.  THE
C  SUBROUTINE RETURNS THE VALUES OF THE NEW ZEROS,
C  'ZERO'('NPREV'+1),.  'CEX' IS A LOGICAL ARRAY...,'ZERO'('N').
C  IF 'CEX'(I) IS .TRUE. THEN THE ITERATION COUNT IS EXCEEDED
C  THEREBY SIGNALLING A POSSIBLE INACCURACY IN THE ROOT.
C
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL NOTFIN,CEX
      INTEGER COUNT
      DOUBLE COMPLEX ZERO,C,DEN,DDF1,DDF2,DDF1P,FZR,FZRD,FZRP,Z,SQR
      DOUBLE COMPLEX H,HPREV
C
      DIMENSION ZERO(*),CEX(*)
C
      EXTERNAL F
C
      DATA AZERO/0./
C
C
      DO 200 I=NPREV+1,N
        COUNT=0
C
  110   CONTINUE
C       COMPUTE THE FUNCTION AT:
C       Z0=ZERO(I)+HINIT, Z1=ZERO(I)-HINIT, Z2=ZERO(I)
C
        Z=ZERO(I)
        H=HINIT
        HPREV=-2.*H
        CALL DFLATE(F,Z+H,I,COUNT,FZR,DDF1P,ZERO,*110)
        CALL DFLATE(F,Z-H,I,COUNT,FZR,FZRP ,ZERO,*110)
        DDF1P=(FZRP-DDF1P)/HPREV
        CALL DFLATE(F,Z  ,I,COUNT,FZR,FZRD ,ZERO,*110)
C
C       REPEAT (UNTIL COUNT EXCEEDS MAXIT OR SATISFACTORY
C               CONVERGENCE)
  120   CONTINUE
          DDF1=(FZRD-FZRP)/H
          DDF2=(DDF1-DDF1P)/(H+HPREV)
          HPREV=H
          DDF1P=DDF1
          C=DDF1+H*DDF2
          SQR=SQRT(C*C-4.*FZRD*DDF2)
          IF (REAL(C)*REAL(SQR)+AIMAG(C)*AIMAG(SQR).LT.0.) THEN
            DEN=C-SQR
          ELSE
            DEN=C+SQR
          END IF
          IF (ABS(DEN).LE.AZERO) DEN=1.
          H=-2.*FZRD/DEN
          FZRP=FZRD
          Z=Z+H
C
  170     IF (COUNT.LE.MAXIT) THEN
C           COUNT NOT EXHAUSTED
            CALL DFLATE(F,Z,I,COUNT,FZR,FZRD,ZERO,*110)
C           CHECK FOR CONVERGENCE
            IF ((ABS(H).GT.EP1*ABS(Z)) .AND.
     +          (MAX(ABS(FZR),ABS(FZRD)).GT.EP2)) THEN
C             CHECK FOR DIVERGENCE
              IF (ABS(FZRD).GE.10.*ABS(FZRP)) THEN
C               DIVERGENCE - ADJUST
                H=H/2.
                Z=Z-H
                GOTO 170
              ELSE
C               NOT DIVERGENT - PRESS ON
                NOTFIN=.TRUE.
              END IF
            ELSE
C             SATISFACTORY CONVERGENCE
              NOTFIN=.FALSE.
              CEX(I)=.FALSE.
            END IF
          ELSE
C           COUNT EXHAUSTED
            NOTFIN=.FALSE.
            CEX(I)=.TRUE.
          END IF
        IF (NOTFIN) GOTO 120
C       UNTIL COUNT EXHAUSTED OR CONVERGENCE ATTAINED
C
        ZERO(I)=Z
  200 CONTINUE
C
C
      RETURN
      END
      SUBROUTINE DFLATE(F,Z,I,COUNT,FZ,FZD,ZERO,*)
C
C  DEFLATION ROUTINE CALLED FROM 'MULLER'
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER COUNT
      DOUBLE COMPLEX FZ,FZD,Z,ZERO(*),DEN
C
      DATA AZERO/0./
C
C
      COUNT=COUNT+1
      CALL F(Z,FZ)
      FZD=FZ
      DO 10 J=2,I
        DEN=Z-ZERO(J-1)
        IF (ABS(DEN).LE.AZERO) THEN
          ZERO(I)=1.0001*Z
          RETURN 1
        ELSE
          FZD=FZD/DEN
        END IF
   10 CONTINUE
C
      RETURN
      END
      SUBROUTINE POLY(Z,FZ)
C
C    'POLY' EVALUATES:
C  FZ = C(0) + C(1)*Z + C(2)*Z**2 + ..... + C(N)*Z**N
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (MSIG=10)
C
      DOUBLE COMPLEX Z,FZ,C(0:MSIG)
C
      COMMON /EXPOLY/ N,C
C
C
      FZ=C(N)
      DO 10 I=N-1,0,-1
        FZ=Z*FZ+C(I)
   10 CONTINUE
C
      RETURN
      END
      SUBROUTINE RF(Z,FZ)
C
C    THIS SUBROUTINE IS USED BY 'EXROOT' IN THE REFINEMENT
C  OF ROOTS BY 'MULLER'.  REMEMBER THAT IF THE REFINEMENT
C  PROCESS WITHIN 'EXROOT' IS REPLACED BY A ROUTINE SUCH
C  AS THE NEWTON-RAPHSON PROCESS THAT EMPLOYS THE DERIVATIVE
C  THEN THIS NEED TO BE RESCALED AS IS INDICATED BELOW.
C
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE COMPLEX Z,FZ,DZ,ZP,CEN
C
      COMMON /RSCALE/ SCALE,CEN
C
C
      ZP=CEN+SCALE*Z
      CALL FNDER(ZP,FZ,DZ)
C     DZ=SCALE*DZ
C     RESCALING OF DERIVATIVE.
C
      RETURN
      END
