from scipy.io import loadmat
import numpy as np
#import libneo.efit2boozer

class tMHD_current:
    """Class to handle (integrated) current from a toroidal MHD code.
    Toroidal MHD code(s) implemented so far: MARS-F"""

    curr_dens = []
    upper_curr_dens = []
    lower_curr_dens = []

    def __init__(self, n_mode=2) -> None:
        self.n_mode = n_mode

    def load_curr_harmonics_MARSF(self, file):
        """Load the current density harmonics from a .mat file generated by MARS-F.
        The current density harmonics are stored in the variables JparU_harm[A/m^2] and JparL_harm[A/m^2].
        The current density harmonics is rescaled to cgs units.
        """
        mat = loadmat(file)

        self.JparU_harm = mat['JparU_harm[A/m^2]'] / 10**5 # conversion from A/m^2 to statA/cm^2
        self.JparL_harm = mat['JparL_harm[A/m^2]'] / 10**5
        self.Mm = mat['Mm'][0]
        self.s = mat['s'][0]
        self.s_rat = mat['s_rat'][0]

    def load_current_MARSF(self, file):
        """Load the parallel shielding current from a .mat file generated by MARS-F.
        The current is given as a function of s and chi (geometrical poloidal angle)."""

        mat = loadmat(file)

        self.JparU = mat['JparU[A/m^2]'] / 10**5 # conversion from A/m^2 to statA/cm^2
        self.JparL = mat['JparL[A/m^2]'] / 10**5
        self.chi = mat['chi'][0]
        self.s = mat['s'][0]
        self.s_rat = mat['s_rat'][0]

    def mix_coil_rows(self, delta_phi = 0.0, coil_curr_scale_l = 1.0, coil_curr_scale_u=1.0):
        """Mix the upper and lower coil current densities by a phase shift delta_phi and a scaling factor coil_curr_scale_l and coil_curr_scale_u."""

        if not type(self.JparU_harm) is None:
            self.Jpar_harm = coil_curr_scale_u * self.JparU_harm + coil_curr_scale_l * self.JparL_harm * np.exp(1j * delta_phi)
        if not type(self.JparU) is None:
            self.Jpar = coil_curr_scale_u * self.JparU + coil_curr_scale_l * self.JparL * np.exp(1j * delta_phi)

    def get_Jpar_over_B0_boozer_harmonics(self):
        """Get the Fourier harmonics in Boozer coordinates of J_parallel / B0."""
        # TODO: Get B0 from libneo.efit2boozer module, use fourier harmonics function in boozer
        pass

    def integrate_curr_dens(self, m_mode=10):
        """Integrate the current density harmonics for a given m_mode. Returns the current for negative and positive m modes.
        The current is given in statA."""

        if not self.loaded_equilibrium:
            print("Error: Equilibrium data not loaded.")
            return
        if not type(self.Jpar_ov_B0_harm) is None:
            print("Error: Jpar over B0 harmonics not available")
            return

        ind_p = np.where(self.Mm[0] == m_mode)[0][0]
        ind_m = np.where(self.Mm[0] == -m_mode)[0][0]

        if ind_p == []:
            print("Error: m_mode not found.")
            return
        if ind_m == []:
            print("Error: n_mode not found.")
            return

        curr_dens_m = self.Jpar_ov_B0_harm[ind_m,:]
        curr_dens_p = self.Jpar_ov_B0_harm[ind_p,:]

        self.current_m = np.trapz(curr_dens_m / self.btor * self.s * np.interp(self.s, self.s_equil, self.q)) * 2.0 * self.psi[-1] 
        self.current_p = np.trapz(curr_dens_p / self.btor * self.s * np.interp(self.s, self.s_equil, self.q)) * 2.0 * self.psi[-1] 

        return [self.current_m, self.current_p]


    def set_equil(self, equil_file, btor_file):
        """Read equilibrium data for the current density integration."""
        try:
            equil = np.loadtxt(equil_file, skiprows=3)
            self.r_eff = equil[:,0]
            self.q = equil[:,1]
            self.psi = equil[:,2]
            self.s_equil = self.psi / self.psi[-1]
            self.loaded_equilibrium = True

            self.btor = np.abs(np.loadtxt(btor_file)[0])
        except:
            print("Error: Could not load equilibrium file or btor file.")
